-- Generated from concept v1 upgrade content/packs/*-vN.json by scripts/render-pack-seed.mjs.
-- Do not edit this file directly.
begin;

create temp table expected_pack_templates (
  id uuid primary key,
  slug text not null unique,
  title text not null,
  target_relationship text not null,
  sensitivity text not null,
  is_active boolean not null
) on commit drop;

create temp table expected_pack_versions (
  id uuid primary key,
  template_id uuid not null,
  version text not null,
  concept_version smallint
) on commit drop;

create temp table expected_pack_cards (
  pack_version_id uuid not null,
  id text not null,
  position smallint not null,
  owner_prompt text not null,
  visitor_prompt text not null,
  option_a text not null,
  option_b text not null,
  is_signature boolean not null,
  concept_context text,
  concept_signals jsonb,
  primary key (pack_version_id, id)
) on commit drop;

insert into expected_pack_templates values
    ('630c20b9-460b-443b-b74b-865d1dfdf5fb'::uuid, 'after-work', '퇴근 후 본캐', 'coworker', 'low', true),
    ('f16e20a8-f2bd-4799-af68-689bbc36ebd5'::uuid, 'algorithm-mirror', '알고리즘이 들킨 날', 'new_connection', 'low', true),
    ('75ccfdf6-bf0d-4fb8-b8a4-a8cb5f933701'::uuid, 'camera-roll', '최근 사진 20장', 'old_friend', 'low', true),
    ('0a9b7ee3-9556-448f-8719-329094601b1a'::uuid, 'comment-section', '내적 댓글창', 'close_relationship', 'medium', true),
    ('e517cc31-8a8c-4156-a2ae-7e8ddb3f6809'::uuid, 'compliment-receipt', '칭찬 영수증', 'close_relationship', 'medium', true),
    ('13131313-1313-4313-8313-131313131313'::uuid, 'coworker', '퇴근 전의 우리', 'coworker', 'low', true),
    ('15299196-d3bf-4f89-be1e-bcc1ea69a904'::uuid, 'deadline-mode', '마감 전의 나', 'coworker', 'low', true),
    ('dec475db-00a1-43ea-91c5-75d32259fd6b'::uuid, 'decision-spiral', '결정은 내일의 나에게', 'close_relationship', 'medium', true),
    ('4c3f9b04-48a2-4dda-a2f9-bfcc101a9565'::uuid, 'emoji-subtitles', '이모지 자막 켜기', 'new_connection', 'low', true),
    ('12121212-1212-4212-8212-121212121212'::uuid, 'first-impression', '첫 장면, 네 버전', 'new_connection', 'low', true),
    ('2cb89681-7c7b-42c4-b1f3-4700d5c17cc0'::uuid, 'friend-fusion', '우리 둘이 섞인다면', 'old_friend', 'low', true),
    ('0e2ac6eb-55f4-40f2-b943-6de54125f6b3'::uuid, 'group-chat-role', '단톡방의 나', 'old_friend', 'low', true),
    ('14141414-1414-4414-8414-141414141414'::uuid, 'honest-self', '말 안 해도 알까?', 'close_relationship', 'medium', true),
    ('f3505753-0118-4778-86fe-19e45d6ec73d'::uuid, 'laugh-track', '웃음 버튼의 위치', 'old_friend', 'low', true),
    ('11111111-1111-4111-8111-111111111111'::uuid, 'old-friend', '우리는 아직도 통하는 편', 'old_friend', 'low', true),
    ('0fbddb18-d125-429e-ad8f-d6581a3af762'::uuid, 'reply-temperature', '읽고도 생각 중', 'new_connection', 'low', true),
    ('a714df85-063e-44f5-a3e5-cc4d6af032bc'::uuid, 'room-temperature', '방 온도와 내 기분', 'close_relationship', 'low', true),
    ('547524ff-9929-44ef-b6d0-70b152b2f1e2'::uuid, 'small-luxury', '작은 사치 연구소', 'close_relationship', 'low', true),
    ('79c2f482-e254-41a5-9e27-296bf416a5d7'::uuid, 'snack-personality', '간식 취향 보고서', 'old_friend', 'low', true),
    ('b5a4e134-2704-40b6-8fa3-7ad47c13e833'::uuid, 'social-battery', '사람들 사이 배터리', 'close_relationship', 'medium', true),
    ('78b2ca60-1f42-4114-a6e0-22155c2d701c'::uuid, 'spontaneous-plan', '갑자기, 지금, 같이?', 'old_friend', 'low', true),
    ('9e0d1399-0314-497d-99aa-79926e226726'::uuid, 'tiny-routine', '혼자만의 루틴', 'close_relationship', 'low', true),
    ('4502a4a8-7ba4-4d3d-9aae-6ca220c57658'::uuid, 'trip-chemistry', '여행 가방의 철학', 'old_friend', 'low', true),
    ('2166c7e7-0d4c-411b-bed2-fe3337a2d24c'::uuid, 'weekend-escape', '주말 사용 설명서', 'old_friend', 'low', true);

insert into expected_pack_versions values
    ('870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid, '630c20b9-460b-443b-b74b-865d1dfdf5fb'::uuid, 'after-work-v3', 1::smallint),
    ('cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid, 'f16e20a8-f2bd-4799-af68-689bbc36ebd5'::uuid, 'algorithm-mirror-v3', 1::smallint),
    ('bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid, '75ccfdf6-bf0d-4fb8-b8a4-a8cb5f933701'::uuid, 'camera-roll-v3', 1::smallint),
    ('f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid, '0a9b7ee3-9556-448f-8719-329094601b1a'::uuid, 'comment-section-v3', 1::smallint),
    ('b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid, 'e517cc31-8a8c-4156-a2ae-7e8ddb3f6809'::uuid, 'compliment-receipt-v3', 1::smallint),
    ('085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid, '13131313-1313-4313-8313-131313131313'::uuid, 'coworker-v2', 1::smallint),
    ('a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid, '15299196-d3bf-4f89-be1e-bcc1ea69a904'::uuid, 'deadline-mode-v2', 1::smallint),
    ('260c451e-cabb-457f-9666-553c752f000b'::uuid, 'dec475db-00a1-43ea-91c5-75d32259fd6b'::uuid, 'decision-spiral-v3', 1::smallint),
    ('9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid, '4c3f9b04-48a2-4dda-a2f9-bfcc101a9565'::uuid, 'emoji-subtitles-v3', 1::smallint),
    ('be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid, '12121212-1212-4212-8212-121212121212'::uuid, 'first-impression-v3', 1::smallint),
    ('645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid, '2cb89681-7c7b-42c4-b1f3-4700d5c17cc0'::uuid, 'friend-fusion-v3', 1::smallint),
    ('107fc85f-8240-4539-a269-3e780629dc6f'::uuid, '0e2ac6eb-55f4-40f2-b943-6de54125f6b3'::uuid, 'group-chat-role-v3', 1::smallint),
    ('b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid, '14141414-1414-4414-8414-141414141414'::uuid, 'honest-self-v3', 1::smallint),
    ('ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid, 'f3505753-0118-4778-86fe-19e45d6ec73d'::uuid, 'laugh-track-v2', 1::smallint),
    ('ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid, '11111111-1111-4111-8111-111111111111'::uuid, 'old-friend-v3', 1::smallint),
    ('9113ceed-fd0c-4523-bb14-316ee823e652'::uuid, '0fbddb18-d125-429e-ad8f-d6581a3af762'::uuid, 'reply-temperature-v3', 1::smallint),
    ('aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid, 'a714df85-063e-44f5-a3e5-cc4d6af032bc'::uuid, 'room-temperature-v3', 1::smallint),
    ('db1136e2-c40b-4354-800a-7938cc73dc47'::uuid, '547524ff-9929-44ef-b6d0-70b152b2f1e2'::uuid, 'small-luxury-v3', 1::smallint),
    ('3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid, '79c2f482-e254-41a5-9e27-296bf416a5d7'::uuid, 'snack-personality-v3', 1::smallint),
    ('62c5934c-b9b7-4df0-a690-c36399237735'::uuid, 'b5a4e134-2704-40b6-8fa3-7ad47c13e833'::uuid, 'social-battery-v3', 1::smallint),
    ('18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid, '78b2ca60-1f42-4114-a6e0-22155c2d701c'::uuid, 'spontaneous-plan-v3', 1::smallint),
    ('7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid, '9e0d1399-0314-497d-99aa-79926e226726'::uuid, 'tiny-routine-v3', 1::smallint),
    ('be9db225-95d3-4da7-8ace-4d8373c17108'::uuid, '4502a4a8-7ba4-4d3d-9aae-6ca220c57658'::uuid, 'trip-chemistry-v3', 1::smallint),
    ('f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid, '2166c7e7-0d4c-411b-bed2-fe3337a2d24c'::uuid, 'weekend-escape-v3', 1::smallint);

insert into expected_pack_cards values
    ('870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid, 'clock-out', 1, '할 일을 마친 직후 나는?', '할 일을 마친 직후 이 사람은?', '바로 다음 즐거움으로 전환한다', '잠깐 멍하니 속도를 늦춘다', true, '퇴근·전환', '[{"conceptId":"reg.transition","directionForOptionA":"a"}]'::jsonb),
    ('870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid, 'route-home', 2, '퇴근길에 기분 전환이 필요하면 나는?', '퇴근길에 기분 전환이 필요할 때 이 사람은?', '다른 길이나 음악으로 분위기를 바꾼다', '익숙한 길을 조용히 걸으며 가라앉힌다', false, '이동', '[{"conceptId":"reg.stimulus","directionForOptionA":"a"}]'::jsonb),
    ('870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid, 'dinner', 3, '저녁을 고를 때 나는?', '저녁을 고를 때 이 사람은?', '간단하게 바로 해결한다', '먹고 싶은 걸 찾아 챙긴다', false, '식사·선택', '[{"conceptId":"dec.convergence","directionForOptionA":"a"}]'::jsonb),
    ('870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid, 'decompress', 4, '하루를 정리하는 방식은?', '이 사람이 하루를 정리하는 방식은?', '누군가와 이야기하며 푼다', '혼자 좋아하는 걸 하며 푼다', false, '회복·감정', '[{"conceptId":"exp.processing","directionForOptionA":"a"},{"conceptId":"reg.source","directionForOptionA":"a"}]'::jsonb),
    ('870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid, 'message-after', 5, '퇴근 후 연락이 오면 나는?', '퇴근 후 연락이 오면 이 사람은?', '가볍게 바로 답한다', '내 시간 뒤에 답한다', false, '연락', '[{"conceptId":"exp.reaction","directionForOptionA":"a"},{"conceptId":"rel.cadence","directionForOptionA":"a"}]'::jsonb),
    ('870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid, 'energy', 6, '저녁 에너지가 남아 있으면 나는?', '저녁 에너지가 남아 있으면 이 사람은?', '밖에서 한 가지 더 한다', '내일을 위해 아껴 둔다', false, '여가·회복', '[{"conceptId":"reg.motion","directionForOptionA":"a"}]'::jsonb),
    ('870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid, 'weeknight', 7, '평일 저녁 약속이 생기면 나는?', '평일 저녁 약속이 생기면 이 사람은?', '퇴근길에 바로 합류한다', '다른 날로 천천히 잡는다', false, '약속', '[{"conceptId":"act.preparation","directionForOptionA":"b"}]'::jsonb),
    ('870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid, 'hobby', 8, '퇴근 후 취미를 할 때 나는?', '퇴근 후 취미를 할 때 이 사람은?', '정해 둔 루틴을 따른다', '그날 끌리는 걸 고른다', false, '취미·일상', '[{"conceptId":"act.routine","directionForOptionA":"a"},{"conceptId":"pref.stability","directionForOptionA":"a"}]'::jsonb),
    ('870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid, 'tomorrow', 9, '집에 들어온 직후 나는?', '집에 들어온 직후 이 사람은?', '씻고 완전히 전환한다', '잠깐 쉬며 천천히 전환한다', false, '귀가·전환', '[{"conceptId":"reg.transition","directionForOptionA":"a"}]'::jsonb),
    ('870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid, 'weekend-countdown', 10, '주말을 기다리는 방식은?', '이 사람이 주말을 기다리는 방식은?', '하고 싶은 계획을 세운다', '그날까지 지금에 집중한다', false, '계획', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid, 'feed-clue', 1, '내 피드가 나를 너무 잘 안다고 느끼면 나는?', '추천 피드가 취향을 너무 잘 안다고 느껴지면 이 사람은?', '추천을 더 깊게 따라간다', '일부러 다른 걸 찾아본다', true, '추천·탐색', '[{"conceptId":"pref.discovery","directionForOptionA":"a"}]'::jsonb),
    ('cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid, 'save-first', 2, '누가 콘텐츠를 추천해 주면 나는?', '누가 콘텐츠를 추천해 주면 이 사람은?', '바로 열어 본다', '저장해 두고 나중에 본다', false, '콘텐츠·반응', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid, 'rabbit-hole', 3, '하나를 보다가 다른 주제로 새면 나는?', '하나를 보다가 다른 주제로 새면 이 사람은?', '끝까지 새 길을 탐험한다', '원래 보려던 곳으로 돌아온다', false, '탐색·변경', '[{"conceptId":"pref.discovery","directionForOptionA":"b"},{"conceptId":"act.adjustment","directionForOptionA":"a"}]'::jsonb),
    ('cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid, 'share-find', 4, '내 취향 저격 콘텐츠를 보면 나는?', '취향에 딱 맞는 콘텐츠를 보면 이 사람은?', '누군가에게 바로 보낸다', '혼자 여러 번 다시 본다', false, '콘텐츠·공유', '[{"conceptId":"exp.reaction","directionForOptionA":"a"},{"conceptId":"rel.cadence","directionForOptionA":"a"}]'::jsonb),
    ('cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid, 'trend-check', 5, '다들 하는 유행을 보면 나는?', '다들 하는 유행을 보면 이 사람은?', '왜 뜨는지 한 번 해본다', '나한테 맞는지부터 본다', false, '유행·시도', '[{"conceptId":"dec.experiment","directionForOptionA":"b"}]'::jsonb),
    ('cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid, 'recommendation', 6, '추천을 받을 때 나는?', '추천을 받을 때 이 사람은?', '비슷한 걸 더 찾아본다', '정반대도 같이 비교한다', false, '추천·비교', '[{"conceptId":"pref.discovery","directionForOptionA":"a"}]'::jsonb),
    ('cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid, 'comment-dive', 7, '흥미로운 영상의 댓글을 볼 때 나는?', '흥미로운 영상의 댓글을 볼 때 이 사람은?', '처음부터 흐름을 따라 차례로 읽는다', '반응이 큰 핵심 댓글부터 찾아본다', false, '콘텐츠·정보', '[{"conceptId":"att.reading","directionForOptionA":"a"}]'::jsonb),
    ('cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid, 'old-favorite', 8, '예전에 좋아한 콘텐츠를 다시 발견하면 나는?', '예전에 좋아한 콘텐츠를 다시 발견하면 이 사람은?', '익숙한 최애로 다시 깊게 들어간다', '지금 끌리는 새로운 취향과 비교한다', false, '취향·기억', '[{"conceptId":"pref.stability","directionForOptionA":"a"}]'::jsonb),
    ('cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid, 'search-style', 9, '궁금한 게 생기면 나는?', '궁금한 게 생기면 이 사람은?', '검색어를 구체적으로 만든다', '대충 넣고 흐름을 따라간다', false, '검색·정보', '[{"conceptId":"act.preparation","directionForOptionA":"a"},{"conceptId":"att.reading","directionForOptionA":"b"}]'::jsonb),
    ('cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid, 'recommend-to-me', 10, '누가 취향을 추천해 달라 하면 나는?', '누가 취향을 추천해 달라 하면 이 사람은?', '내 최애 하나를 강하게 민다', '상대 취향부터 물어본다', false, '추천·설명', '[{"conceptId":"att.story","directionForOptionA":"b"}]'::jsonb),
    ('bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid, 'first-photo', 1, '재밌는 순간이 오면 나는?', '재밌는 순간이 오면 이 사람은?', '바로 사진부터 남긴다', '먼저 그 순간을 즐긴다', true, '경험·기록', '[{"conceptId":"att.experience","directionForOptionA":"a"}]'::jsonb),
    ('bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid, 'food-photo', 2, '맛있는 음식 앞에서 나는?', '맛있는 음식 앞에서 이 사람은?', '예쁘게 찍고 먹는다', '따뜻할 때 먼저 먹는다', false, '식사·기록', '[{"conceptId":"att.experience","directionForOptionA":"a"}]'::jsonb),
    ('bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid, 'selfie', 3, '내 사진을 찍을 때 나는?', '자기 사진을 찍을 때 이 사람은?', '여러 장 중 마음에 드는 걸 고른다', '한 장의 자연스러운 컷을 남긴다', false, '자기표현·선택', '[{"conceptId":"dec.convergence","directionForOptionA":"b"}]'::jsonb),
    ('bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid, 'friend-photo', 4, '친구와 사진을 같이 만들 때 우리는?', '친구와 사진을 같이 만들 때 이 사람은?', '같은 박자에 맞춰 포즈를 잡는다', '한 명은 구도, 한 명은 표정을 맡는다', false, '친구·사진', '[{"conceptId":"coop.sync","directionForOptionA":"a"}]'::jsonb),
    ('bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid, 'cleanup', 5, '사진이 쌓이면 나는?', '사진이 쌓이면 이 사람은?', '틈틈이 정리한다', '필요할 때 찾아본다', false, '정리·일상', '[{"conceptId":"act.routine","directionForOptionA":"a"}]'::jsonb),
    ('bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid, 'old-album', 6, '예전 사진을 보면 나는?', '예전 사진을 보면 이 사람은?', '그날 이야기를 떠올린다', '그때의 분위기를 다시 느낀다', false, '기억', '[{"conceptId":"att.memory","directionForOptionA":"a"}]'::jsonb),
    ('bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid, 'share-photo', 7, '함께 찍은 사진을 고를 때 나는?', '함께 찍은 사진을 고를 때 이 사람은?', '바로 보내서 같이 본다', '마음에 드는 걸 골라 보낸다', false, '사진·공유', '[{"conceptId":"exp.reaction","directionForOptionA":"a"},{"conceptId":"dec.revision","directionForOptionA":"a"}]'::jsonb),
    ('bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid, 'screenshot', 8, '재밌는 화면을 발견하면 나는?', '재밌는 화면을 발견하면 이 사람은?', '바로 캡처하며 따라간다', '먼저 끝까지 본 뒤 필요한 장면을 남긴다', false, '저장·공유', '[{"conceptId":"att.experience","directionForOptionA":"a"}]'::jsonb),
    ('bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid, 'landscape', 9, '여행 풍경을 나중에 떠올릴 때 나는?', '여행 풍경을 나중에 떠올릴 때 이 사람은?', '빛과 장소 같은 구체적인 장면이 먼저 난다', '그때의 기분과 분위기가 먼저 난다', false, '풍경·기억', '[{"conceptId":"att.memory","directionForOptionA":"a"}]'::jsonb),
    ('bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid, 'favorite', 10, '친구에게 사진 한 장을 보여준다면 나는?', '친구에게 사진 한 장을 보여준다면 이 사람은?', '전후 맥락이 담긴 장면을 고른다', '핵심 표정이 바로 보이는 장면을 고른다', false, '사진·선택', '[{"conceptId":"att.story","directionForOptionA":"a"}]'::jsonb),
    ('f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid, 'surprise-thought', 1, '뜻밖의 일이 생기면 내 머릿속은?', '뜻밖의 일이 생기면 이 사람 머릿속은?', '말로 바로 나오는 편이다', '속으로 먼저 여러 번 생각한다', true, '돌발·생각', '[{"conceptId":"exp.reaction","directionForOptionA":"a"},{"conceptId":"exp.processing","directionForOptionA":"a"}]'::jsonb),
    ('f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid, 'replay', 2, '대화가 끝난 뒤 머릿속 첫 반응은?', '대화가 끝난 뒤 이 사람 머릿속 첫 반응은?', '방금 한 말을 다시 재생한다', '다음에 할 말을 미리 붙인다', false, '대화·전환', '[{"conceptId":"reg.transition","directionForOptionA":"b"}]'::jsonb),
    ('f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid, 'awkward-moment', 3, '민망한 순간이 오면 나는?', '민망한 순간이 오면 이 사람은?', '웃으며 바로 넘긴다', '혼자 조금 더 곱씹는다', false, '민망함·전환', '[{"conceptId":"exp.reaction","directionForOptionA":"a"},{"conceptId":"reg.transition","directionForOptionA":"a"}]'::jsonb),
    ('f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid, 'idea', 4, '좋은 생각이 떠오르면 나는?', '좋은 생각이 떠오르면 이 사람은?', '누군가에게 말하며 키운다', '혼자 메모하며 다듬는다', false, '아이디어', '[{"conceptId":"exp.processing","directionForOptionA":"a"}]'::jsonb),
    ('f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid, 'choice-voice', 5, '결정을 내리기 직전 내적 댓글은?', '결정을 내리기 직전 이 사람의 내적 댓글은?', '이유 하나면 충분하다고 한다', '놓친 조건이 없나 다시 묻는다', false, '선택', '[{"conceptId":"dec.convergence","directionForOptionA":"a"}]'::jsonb),
    ('f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid, 'quiet', 6, '생각이 복잡할 때 조용한 시간이 생기면 나는?', '생각이 복잡할 때 조용한 시간이 생기면 이 사람은?', '음악이나 산책으로 자극을 바꾼다', '소리를 줄이고 가만히 가라앉힌다', false, '혼자·생각', '[{"conceptId":"reg.stimulus","directionForOptionA":"a"}]'::jsonb),
    ('f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid, 'mistake', 7, '실수를 알아차리면 나는?', '실수를 알아차리면 이 사람은?', '가장 작은 수정부터 바로 시작한다', '전체 영향을 먼저 파악한 뒤 움직인다', false, '실수', '[{"conceptId":"act.start","directionForOptionA":"a"}]'::jsonb),
    ('f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid, 'compliment-thought', 8, '오래 남은 칭찬을 다시 떠올릴 때 나는?', '오래 남은 칭찬을 다시 떠올릴 때 이 사람은?', '그때의 장면과 맥락까지 펼쳐 본다', '핵심 한마디만 선명하게 기억한다', false, '칭찬·기억', '[{"conceptId":"att.story","directionForOptionA":"a"}]'::jsonb),
    ('f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid, 'plan-thought', 9, '새 계획 앞에서 머릿속 첫 반응은?', '새 계획 앞에서 이 사람 머릿속 첫 반응은?', '해볼 장면부터 떠올린다', '필요한 준비부터 떠올린다', false, '계획', '[{"conceptId":"act.preparation","directionForOptionA":"b"}]'::jsonb),
    ('f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid, 'share-thought', 10, '마음에 걸리는 생각이 있으면 나는?', '마음에 걸리는 생각이 있으면 이 사람은?', '믿는 사람에게 말해 본다', '시간을 두고 혼자 정리한다', false, '감정·공유', '[{"conceptId":"exp.processing","directionForOptionA":"a"},{"conceptId":"reg.source","directionForOptionA":"a"}]'::jsonb),
    ('b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid, 'receive', 1, '칭찬을 들으면 나는?', '칭찬을 들으면 이 사람은?', '기분 좋은 티가 바로 난다', '쑥스러워도 조용히 기억한다', true, '칭찬·반응', '[{"conceptId":"exp.intensity","directionForOptionA":"a"},{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid, 'give', 2, '좋은 점을 발견하면 나는?', '좋은 점을 발견하면 이 사람은?', '그 자리에서 바로 말한다', '딱 맞는 순간까지 아껴 둔다', false, '칭찬·표현', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid, 'specific', 3, '누군가를 칭찬할 때 나는?', '이 사람이 누군가를 칭찬할 때는?', '구체적인 장면을 말한다', '느낀 마음을 크게 전한다', false, '칭찬·기억', '[{"conceptId":"att.memory","directionForOptionA":"a"}]'::jsonb),
    ('b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid, 'achievement', 4, '함께 만든 성과를 칭찬할 때 나는?', '함께 만든 성과를 칭찬할 때 이 사람은?', '서로 속도를 맞춘 과정을 말한다', '각자 다른 역할로 채운 부분을 말한다', false, '성취', '[{"conceptId":"coop.sync","directionForOptionA":"a"}]'::jsonb),
    ('b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid, 'awkward', 5, '갑자기 다정한 말을 들으면 나는?', '갑자기 다정한 말을 들으면 이 사람은?', '장난으로 받아친다', '고맙다고 그대로 받는다', false, '칭찬·표현', '[{"conceptId":"exp.form","directionForOptionA":"a"}]'::jsonb),
    ('b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid, 'encourage', 6, '힘들어 보이는 사람에게 나는?', '힘들어 보이는 사람에게 이 사람은?', '실질적인 도움을 제안한다', '먼저 마음을 알아준다', false, '위로·도움', '[{"conceptId":"coop.support","directionForOptionA":"a"}]'::jsonb),
    ('b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid, 'small-win', 7, '작은 성공이 생기면 나는?', '작은 성공이 생기면 이 사람은?', '누군가에게 바로 알린다', '혼자 뿌듯해하며 쌓아 둔다', false, '성취·공유', '[{"conceptId":"exp.intensity","directionForOptionA":"a"},{"conceptId":"reg.source","directionForOptionA":"a"}]'::jsonb),
    ('b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid, 'feedback', 8, '좋은 피드백을 받으면 다음에는?', '좋은 피드백을 받으면 다음에 이 사람은?', '잘된 방식을 그대로 한 번 더 써 본다', '한 부분을 바꿔 더 나은지 확인한다', false, '피드백', '[{"conceptId":"dec.revision","directionForOptionA":"a"}]'::jsonb),
    ('b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid, 'support', 9, '친구가 스스로를 깎아내리면 나는?', '친구가 스스로를 깎아내리면 이 사람은?', '구체적으로 잘한 점을 말한다', '그 말이 나온 마음부터 묻는다', false, '위로·도움', '[{"conceptId":"coop.support","directionForOptionA":"a"}]'::jsonb),
    ('b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid, 'memory', 10, '누군가에게 오래 남을 칭찬을 한다면?', '누군가에게 오래 남을 칭찬을 할 때 이 사람은?', '구체적인 장면과 이유를 자세히 말한다', '가장 중요한 한마디로 전한다', false, '칭찬·기억', '[{"conceptId":"att.story","directionForOptionA":"a"}]'::jsonb),
    ('085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid, 'unclear-task', 1, '업무가 애매하게 주어지면 나는?', '업무가 애매하게 주어지면 이 사람은?', '먼저 기준을 질문한다', '가능한 안을 만들어 확인한다', true, '업무·애매함', '[{"conceptId":"coop.ambiguity","directionForOptionA":"a"}]'::jsonb),
    ('085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid, 'meeting', 2, '회의에서 의견이 생기면 나는?', '회의에서 의견이 생기면 이 사람은?', '떠오른 때 바로 말한다', '정리한 뒤 차례에 말한다', false, '회의·표현', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid, 'focus', 3, '집중이 필요할 때 나는?', '집중이 필요할 때 이 사람은?', '주변을 정돈하고 몰입한다', '장소나 일을 바꿔 리듬을 만든다', false, '업무·집중', '[{"conceptId":"reg.stimulus","directionForOptionA":"b"}]'::jsonb),
    ('085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid, 'deadline', 4, '마감이 있는 일을 할 때 나는?', '마감이 있는 일을 할 때 이 사람은?', '여유 있게 나눠 진행한다', '집중할 시간을 잡아 한 번에 진행한다', false, '업무·마감', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid, 'feedback', 5, '피드백을 받으면 나는?', '피드백을 받으면 이 사람은?', '바로 질문하며 이해한다', '혼자 정리한 뒤 반영한다', false, '업무·피드백', '[{"conceptId":"exp.processing","directionForOptionA":"a"}]'::jsonb),
    ('085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid, 'new-colleague', 6, '새 동료와 가까워질 때 나는 먼저?', '새 동료와 가까워질 때 이 사람은 먼저?', '말을 걸고 함께 다닌다', '업무 중 필요한 순간을 돕는다', false, '동료·관계', '[{"conceptId":"rel.entry","directionForOptionA":"a"}]'::jsonb),
    ('085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid, 'break', 7, '점심이나 쉬는 시간에 나는?', '점심이나 쉬는 시간에 이 사람은?', '동료와 함께 쉬며 충전한다', '혼자만의 시간으로 충전한다', false, '업무·회복', '[{"conceptId":"reg.source","directionForOptionA":"a"}]'::jsonb),
    ('085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid, 'plan-change', 8, '계획이 갑자기 바뀌면 나는 먼저?', '계획이 갑자기 바뀌면 이 사람은 먼저?', '새 우선순위를 정한다', '영향받는 사람과 일을 확인한다', false, '업무·변경', '[{"conceptId":"att.reading","directionForOptionA":"b"}]'::jsonb),
    ('085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid, 'ask-help', 9, '동료의 도움이 필요할 때 나는?', '동료의 도움이 필요할 때 이 사람은?', '상황을 설명하고 바로 요청한다', '내가 해본 뒤 막힌 부분을 묻는다', false, '업무·도움', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid, 'share-work', 10, '일을 마친 뒤 나는?', '일을 마친 뒤 이 사람은?', '바로 공유하고 의견을 받는다', '한 번 더 점검한 뒤 공유한다', false, '업무·공유', '[{"conceptId":"exp.reaction","directionForOptionA":"a"},{"conceptId":"dec.revision","directionForOptionA":"a"}]'::jsonb),
    ('a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid, 'start-point', 1, '마감이 잡히면 나는?', '마감이 잡히면 이 사람은?', '바로 첫 조각부터 시작한다', '전체 그림을 잡은 뒤 움직인다', true, '마감·시작', '[{"conceptId":"act.start","directionForOptionA":"a"}]'::jsonb),
    ('a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid, 'calendar', 2, '할 일이 많아지면 나는?', '할 일이 많아지면 이 사람은?', '일정을 눈에 보이게 나눈다', '급한 순서대로 바로 처리한다', false, '업무·순서', '[{"conceptId":"act.preparation","directionForOptionA":"a"},{"conceptId":"att.reading","directionForOptionA":"a"}]'::jsonb),
    ('a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid, 'focus-place', 3, '집중이 안 될 때 나는?', '집중이 안 될 때 이 사람은?', '환경을 바꿔 다시 시작한다', '작은 목표를 정해 버틴다', false, '집중·변경', '[{"conceptId":"act.adjustment","directionForOptionA":"a"}]'::jsonb),
    ('a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid, 'first-draft', 4, '처음 결과물을 만들 때 나는?', '처음 결과물을 만들 때 이 사람은?', '일단 빠르게 초안을 낸다', '기준에 맞게 다듬어 시작한다', false, '초안·애매함', '[{"conceptId":"act.start","directionForOptionA":"a"},{"conceptId":"coop.ambiguity","directionForOptionA":"b"}]'::jsonb),
    ('a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid, 'help-signal', 5, '막히는 일이 생기면 나는?', '막히는 일이 생기면 이 사람은?', '일찍 도움을 요청한다', '가능한 데까지 혼자 풀어본다', false, '업무·도움', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid, 'break-time', 6, '바쁜 중간 쉬는 시간 나는?', '바쁜 중간 쉬는 시간 이 사람은?', '짧게라도 몸을 움직인다', '흐름이 끊기지 않게 계속 간다', false, '업무·회복', '[{"conceptId":"reg.motion","directionForOptionA":"a"}]'::jsonb),
    ('a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid, 'feedback-time', 7, '중간 피드백을 받을 때 나는?', '중간 피드백을 받을 때 이 사람은?', '바로 공유해 방향을 맞춘다', '한 번 더 완성도를 올려 공유한다', false, '업무·피드백', '[{"conceptId":"exp.reaction","directionForOptionA":"a"},{"conceptId":"coop.role","directionForOptionA":"a"}]'::jsonb),
    ('a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid, 'deadline-night', 8, '마감 직전 나는?', '마감 직전 이 사람은?', '우선 제출 가능한 상태를 만든다', '끝까지 디테일을 다듬는다', false, '마감·선택', '[{"conceptId":"dec.convergence","directionForOptionA":"a"}]'::jsonb),
    ('a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid, 'done', 9, '일을 끝낸 뒤 나는?', '일을 끝낸 뒤 이 사람은?', '바로 다음 일을 정리한다', '잠깐 성취감을 즐긴다', false, '완료·전환', '[{"conceptId":"reg.transition","directionForOptionA":"a"}]'::jsonb),
    ('a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid, 'rematch', 10, '다음번 같은 일이 오면 나는?', '다음번 같은 일이 오면 이 사람은?', '이번의 방식을 반복한다', '새 방법을 하나 바꿔 본다', false, '반복·변경', '[{"conceptId":"pref.familiarity","directionForOptionA":"a"},{"conceptId":"act.adjustment","directionForOptionA":"b"}]'::jsonb),
    ('260c451e-cabb-457f-9666-553c752f000b'::uuid, 'menu', 1, '고를 게 너무 많을 때 나는?', '고를 게 너무 많을 때 이 사람은?', '기준을 하나 정해 빠르게 고른다', '후회 없게 끝까지 비교한다', true, '선택', '[{"conceptId":"dec.convergence","directionForOptionA":"a"}]'::jsonb),
    ('260c451e-cabb-457f-9666-553c752f000b'::uuid, 'recommendation', 2, '둘이 메뉴를 고를 때 더 편한 방식은?', '둘이 메뉴를 고를 때 이 사람이 더 편해하는 방식은?', '둘 다 비슷하게 원하는 메뉴를 찾는다', '한 명은 후보를, 한 명은 결정을 맡는다', false, '선택·피로', '[{"conceptId":"coop.sync","directionForOptionA":"a"}]'::jsonb),
    ('260c451e-cabb-457f-9666-553c752f000b'::uuid, 'big-choice', 3, '결정할 시간이 넉넉하면 나는?', '결정할 시간이 넉넉하면 이 사람은?', '일찍 정해 마음을 비운다', '마지막까지 가능성을 열어 둔다', false, '중요한선택', '[{"conceptId":"dec.openness","directionForOptionA":"a"}]'::jsonb),
    ('260c451e-cabb-457f-9666-553c752f000b'::uuid, 'coin-flip', 4, '둘 중 하나를 못 고르면 나는?', '둘 중 하나를 못 고르면 이 사람은?', '마감 시간을 정해 고른다', '하루 더 두고 본다', false, '선택·시간', '[{"conceptId":"dec.convergence","directionForOptionA":"a"}]'::jsonb),
    ('260c451e-cabb-457f-9666-553c752f000b'::uuid, 'risk', 5, '새로운 선택 앞에서 나는?', '새로운 선택 앞에서 이 사람은?', '해보면서 배우는 쪽을 고른다', '안전한 기준점을 먼저 찾는다', false, '선택·시도', '[{"conceptId":"dec.experiment","directionForOptionA":"b"}]'::jsonb),
    ('260c451e-cabb-457f-9666-553c752f000b'::uuid, 'purchase', 6, '작은 예산으로 사고 싶은 게 여러 개라면?', '작은 예산으로 사고 싶은 게 여러 개라면 이 사람은?', '가장 마음에 드는 하나를 고른다', '작은 즐거움 여러 개를 고른다', false, '소비·선택', '[{"conceptId":"pref.focus","directionForOptionA":"a"}]'::jsonb),
    ('260c451e-cabb-457f-9666-553c752f000b'::uuid, 'plan-change', 7, '정한 계획을 바꿀 때 나는?', '정한 계획을 바꿀 때 이 사람은?', '더 나은 이유가 있으면 바꾼다', '처음 정한 약속을 지킨다', false, '계획·변경', '[{"conceptId":"act.adjustment","directionForOptionA":"a"},{"conceptId":"dec.revision","directionForOptionA":"b"}]'::jsonb),
    ('260c451e-cabb-457f-9666-553c752f000b'::uuid, 'advice', 8, '누가 선택을 물어보면 나는?', '누가 선택을 물어보면 이 사람은?', '내가 고를 답을 말해 준다', '상대 기준을 같이 정리한다', false, '조언·애매함', '[{"conceptId":"coop.ambiguity","directionForOptionA":"b"},{"conceptId":"att.story","directionForOptionA":"b"}]'::jsonb),
    ('260c451e-cabb-457f-9666-553c752f000b'::uuid, 'regret', 9, '선택 뒤 아쉬움이 남으면 나는?', '선택 뒤 아쉬움이 남으면 이 사람은?', '다음 선택의 기준으로 쓴다', '좋았던 점을 먼저 찾는다', false, '선택·회고', '[{"conceptId":"act.adjustment","directionForOptionA":"a"}]'::jsonb),
    ('260c451e-cabb-457f-9666-553c752f000b'::uuid, 'easy-day', 10, '결정 피로가 쌓인 날 하나를 골랐다면?', '결정 피로가 쌓인 날 하나를 고른 뒤 이 사람은?', '더 보지 않고 그 선택으로 끝낸다', '혹시 몰라 후보 하나는 남겨 둔다', false, '선택·피로', '[{"conceptId":"dec.openness","directionForOptionA":"a"}]'::jsonb),
    ('9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid, 'reaction-style', 1, '말보다 반응이 먼저 나올 때 나는?', '말보다 반응이 먼저 나올 때 이 사람은?', '이모지나 짤로 답한다', '짧은 문장으로 바로 말한다', true, '메시지·표현', '[{"conceptId":"exp.form","directionForOptionA":"a"}]'::jsonb),
    ('9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid, 'funny-post', 2, '웃긴 걸 발견하면 나는?', '웃긴 걸 발견하면 이 사람은?', '딱 생각나는 사람에게 보낸다', '내 저장 목록에 넣어 둔다', false, '콘텐츠·공유', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid, 'tone', 3, '장난을 칠 때 나는?', '장난을 칠 때 이 사람은?', '표정이나 이모지를 덧붙인다', '말투만으로 전달한다', false, '장난·표현', '[{"conceptId":"exp.form","directionForOptionA":"a"}]'::jsonb),
    ('9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid, 'inside-reference', 4, '상대가 낯선 표현을 쓰면 나는?', '상대가 낯선 표현을 쓰면 이 사람은?', '뜻을 물어보고 따라 써 본다', '맥락을 보며 천천히 익힌다', false, '새표현·관계', '[{"conceptId":"rel.distance","directionForOptionA":"a"},{"conceptId":"dec.experiment","directionForOptionA":"b"}]'::jsonb),
    ('9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid, 'misread', 5, '장난이 오해될 것 같으면 나는?', '장난이 오해될 것 같으면 이 사람은?', '표정 이모지를 하나 붙인다', '짧게 진심을 덧붙인다', false, '오해·표현', '[{"conceptId":"exp.form","directionForOptionA":"a"}]'::jsonb),
    ('9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid, 'gif-choice', 6, '새 이모지 목록에서 반응 하나를 찾을 때 나는?', '새 이모지 목록에서 반응 하나를 찾을 때 이 사람은?', '처음부터 하나씩 차례로 훑는다', '눈에 띄는 핵심 반응부터 고른다', false, '메시지·정보', '[{"conceptId":"att.reading","directionForOptionA":"a"}]'::jsonb),
    ('9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid, 'new-slang', 7, '새로운 말투를 들으면 나는?', '새로운 말투를 들으면 이 사람은?', '재밌으면 바로 써 본다', '어울릴 때까지 지켜본다', false, '새표현·시도', '[{"conceptId":"rel.distance","directionForOptionA":"a"},{"conceptId":"dec.experiment","directionForOptionA":"b"}]'::jsonb),
    ('9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid, 'laughter', 8, '텍스트로 웃음을 표현할 때 나는?', '텍스트로 웃음을 표현할 때 이 사람은?', '크고 분명하게 반응한다', '조용히 한 마디를 남긴다', false, '메시지·반응', '[{"conceptId":"exp.intensity","directionForOptionA":"a"}]'::jsonb),
    ('9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid, 'reply-context', 9, '한 장면을 채팅으로 설명해야 할 때 나는?', '한 장면을 채팅으로 설명해야 할 때 이 사람은?', '이모지를 이어 맥락을 펼친다', '핵심이 되는 한 문장만 보낸다', false, '메시지·설명', '[{"conceptId":"att.story","directionForOptionA":"a"}]'::jsonb),
    ('9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid, 'translate', 10, '상대의 이모지를 못 알아들으면 나는?', '상대의 이모지를 못 알아들으면 이 사람은?', '뜻을 바로 물어본다', '내가 이해한 뜻을 먼저 말해 확인한다', false, '메시지·애매함', '[{"conceptId":"coop.ambiguity","directionForOptionA":"a"}]'::jsonb),
    ('be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid, 'first-move', 1, '처음 만난 자리에서 나는?', '처음 만난 자리에서 이 사람은?', '먼저 말을 건다', '상대가 말을 걸면 자연스럽게 이어 간다', true, '첫만남', '[{"conceptId":"rel.entry","directionForOptionA":"a"}]'::jsonb),
    ('be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid, 'first-topic', 2, '낯선 모임에서 대화를 이어갈 때 나는?', '낯선 모임에서 대화를 이어갈 때 이 사람은?', '여러 사람과 짧게 공통점을 찾는다', '한 사람의 이야기를 오래 파고든다', false, '첫대화', '[{"conceptId":"rel.range","directionForOptionA":"a"}]'::jsonb),
    ('be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid, 'group-entry', 3, '낯선 사람들이 모인 자리에 가면 나는?', '낯선 사람들이 모인 자리에 가면 이 사람은?', '여러 사람에게 두루 인사한다', '한두 사람과 먼저 친해진다', false, '낯선모임', '[{"conceptId":"rel.range","directionForOptionA":"a"}]'::jsonb),
    ('be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid, 'silence', 4, '대화가 잠시 끊기면 나는?', '대화가 잠시 끊기면 이 사람은?', '새 화제를 꺼낸다', '잠깐의 침묵도 편하게 둔다', false, '대화·진입', '[{"conceptId":"rel.entry","directionForOptionA":"a"}]'::jsonb),
    ('be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid, 'interest', 5, '상대 이야기에 관심을 보일 때 나는 주로?', '상대 이야기에 관심을 보일 때 이 사람은 주로?', '표정과 맞장구로 보여 준다', '이어지는 질문으로 보여 준다', false, '관심·표현', '[{"conceptId":"exp.form","directionForOptionA":"a"}]'::jsonb),
    ('be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid, 'humor', 6, '첫 만남에서 웃음이 생기면 나는?', '첫 만남에서 웃음이 생기면 이 사람은?', '먼저 농담을 꺼낸다', '상대 농담에 크게 반응한다', false, '첫만남·반응', '[{"conceptId":"rel.entry","directionForOptionA":"a"}]'::jsonb),
    ('be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid, 'warm-up', 7, '새로운 사람과 가까워질 때 나는?', '새로운 사람과 가까워질 때 이 사람은?', '짧은 시간에도 금방 편해진다', '몇 번 만나며 천천히 편해진다', false, '관계·거리', '[{"conceptId":"rel.distance","directionForOptionA":"a"}]'::jsonb),
    ('be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid, 'meet-again', 8, '한 번 만난 사람을 다시 보면 나는?', '한 번 만난 사람을 다시 보면 이 사람은?', '지난 이야기를 바로 이어 간다', '새 근황부터 천천히 다시 맞춘다', false, '재회·대화', '[{"conceptId":"rel.distance","directionForOptionA":"a"}]'::jsonb),
    ('be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid, 'follow-up', 9, '처음 만난 뒤 연락할 때 나는?', '처음 만난 뒤 연락할 때 이 사람은?', '먼저 짧게 안부를 보낸다', '다음에 만날 계기가 생기면 연락한다', false, '첫만남·연락', '[{"conceptId":"rel.cadence","directionForOptionA":"a"}]'::jsonb),
    ('be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid, 'outfit', 10, '처음 만나는 날 옷을 고를 때 나는?', '처음 만나는 날 옷을 고를 때 이 사람은?', '익숙한 조합을 전날 미리 정해 둔다', '나가기 직전 새로운 포인트를 그날 고른다', false, '첫인상·준비', '[{"conceptId":"act.preparation","directionForOptionA":"a"},{"conceptId":"pref.familiarity","directionForOptionA":"a"}]'::jsonb),
    ('645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid, 'combined-plan', 1, '친구와 내가 한 팀이면 나는?', '친구와 한 팀이 되면 이 사람은?', '시작을 끌어가는 역할', '마무리를 챙기는 역할', true, '협업·역할', '[{"conceptId":"coop.role","directionForOptionA":"a"}]'::jsonb),
    ('645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid, 'trip-team', 2, '여행을 같이 준비하면 나는?', '여행을 같이 준비하면 이 사람은?', '가고 싶은 곳을 모은다', '현실적인 동선을 만든다', false, '여행·협업', '[{"conceptId":"act.preparation","directionForOptionA":"b"},{"conceptId":"coop.ambiguity","directionForOptionA":"a"}]'::jsonb),
    ('645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid, 'game-team', 3, '게임을 함께 시작하면 우리는?', '게임을 함께 시작하면 이 사람은?', '같은 속도로 규칙을 익혀 간다', '한 명은 규칙, 한 명은 분위기를 맡는다', false, '놀이·협업', '[{"conceptId":"coop.sync","directionForOptionA":"a"}]'::jsonb),
    ('645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid, 'food-team', 4, '메뉴를 같이 고르면 나는?', '메뉴를 같이 고르면 이 사람은?', '후보를 여러 개 던진다', '마지막 선택을 정리한다', false, '식사·협업', '[{"conceptId":"dec.convergence","directionForOptionA":"b"},{"conceptId":"coop.role","directionForOptionA":"a"}]'::jsonb),
    ('645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid, 'problem-team', 5, '갑작스러운 문제가 생기면 나는?', '갑작스러운 문제가 생기면 이 사람은?', '해결책부터 찾는다', '사람들 기분부터 살핀다', false, '문제·도움', '[{"conceptId":"coop.support","directionForOptionA":"a"}]'::jsonb),
    ('645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid, 'photo-team', 6, '사진을 함께 정리할 때 나는?', '사진을 함께 정리할 때 이 사람은?', '먼저 찍을 장면과 구도를 연다', '마지막 사진을 고르고 마무리한다', false, '사진·협업', '[{"conceptId":"coop.role","directionForOptionA":"a"}]'::jsonb),
    ('645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid, 'gift-team', 7, '선물 단서를 같이 모을 때 나는?', '선물 단서를 같이 모을 때 이 사람은?', '들은 이야기를 차례로 정리한다', '가장 중요한 취향부터 찾는다', false, '선물·정보', '[{"conceptId":"att.reading","directionForOptionA":"a"}]'::jsonb),
    ('645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid, 'story-team', 8, '둘만 아는 이야기가 생기면 나는?', '둘만 아는 이야기가 생기면 이 사람은?', '자세한 장면을 기억한다', '그때의 감정을 기억한다', false, '친구·기억', '[{"conceptId":"att.memory","directionForOptionA":"a"}]'::jsonb),
    ('645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid, 'support-team', 9, '친구가 지치면 나는?', '친구가 지치면 이 사람은?', '필요한 일을 같이 한다', '옆에 있어 주며 듣는다', false, '친구·도움', '[{"conceptId":"coop.support","directionForOptionA":"a"}]'::jsonb),
    ('645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid, 'best-combo', 10, '친구와 내가 잘 맞는 이유는?', '이 사람과 친구가 잘 맞는 이유는?', '비슷한 속도로 함께 움직여서', '서로 다른 빈틈을 채워 줘서', false, '협업·조율', '[{"conceptId":"coop.sync","directionForOptionA":"a"}]'::jsonb),
    ('107fc85f-8240-4539-a269-3e780629dc6f'::uuid, 'new-message', 1, '단체 채팅방에 새 소식이 올라오면 나는?', '단체 채팅방에 새 소식이 올라오면 이 사람은?', '바로 리액션을 남긴다', '내용을 다 읽고 한마디 한다', true, '단체채팅·반응', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('107fc85f-8240-4539-a269-3e780629dc6f'::uuid, 'plan-maker', 2, '모임 얘기가 나오면 나는?', '모임 얘기가 나오면 이 사람은?', '날짜 후보를 먼저 던진다', '사람들 반응을 보고 고른다', false, '모임·애매함', '[{"conceptId":"coop.role","directionForOptionA":"a"},{"conceptId":"coop.ambiguity","directionForOptionA":"b"}]'::jsonb),
    ('107fc85f-8240-4539-a269-3e780629dc6f'::uuid, 'photo-drop', 3, '사진이 한꺼번에 올라오면 나는?', '사진이 한꺼번에 올라오면 이 사람은?', '마음에 드는 한 장을 고른다', '그때 있었던 일을 다시 꺼낸다', false, '사진·기억', '[{"conceptId":"att.experience","directionForOptionA":"a"}]'::jsonb),
    ('107fc85f-8240-4539-a269-3e780629dc6f'::uuid, 'silence-break', 4, '채팅방이 조용해지면 나는?', '채팅방이 조용해지면 이 사람은?', '새로운 소재를 올린다', '조용한 상태도 그냥 둔다', false, '단체채팅·진입', '[{"conceptId":"rel.entry","directionForOptionA":"a"}]'::jsonb),
    ('107fc85f-8240-4539-a269-3e780629dc6f'::uuid, 'notification', 5, '알림이 많이 쌓이면 나는?', '알림이 많이 쌓이면 이 사람은?', '틈날 때 처음부터 읽는다', '중요한 부분부터 훑는다', false, '단체채팅·정보', '[{"conceptId":"att.reading","directionForOptionA":"a"}]'::jsonb),
    ('107fc85f-8240-4539-a269-3e780629dc6f'::uuid, 'birthday', 6, '누군가 생일인 걸 알면 나는?', '누군가 생일인 걸 알면 이 사람은?', '바로 축하 메시지를 보낸다', '센스 있는 사진이나 말을 찾는다', false, '축하·반응', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('107fc85f-8240-4539-a269-3e780629dc6f'::uuid, 'decision', 7, '의견이 갈리는 단체 채팅에서 나는?', '의견이 갈리는 단체 채팅에서 이 사람은?', '모두가 함께 갈 수 있는 안을 맞춘다', '역할을 나눠 각자 원하는 부분을 채운다', false, '의견조율', '[{"conceptId":"coop.sync","directionForOptionA":"a"}]'::jsonb),
    ('107fc85f-8240-4539-a269-3e780629dc6f'::uuid, 'inside-joke', 8, '우리끼리 아는 얘기를 새 사람에게 전한다면?', '우리끼리 아는 얘기를 새 사람에게 전할 때 이 사람은?', '처음부터 맥락을 자세히 풀어 준다', '웃긴 핵심 장면만 짧게 전한다', false, '친구·이야기', '[{"conceptId":"att.story","directionForOptionA":"a"}]'::jsonb),
    ('107fc85f-8240-4539-a269-3e780629dc6f'::uuid, 'exit', 9, '대화가 너무 빨라지면 나는?', '대화가 너무 빨라지면 이 사람은?', '흐름에 맞춰 짧게 낀다', '나중에 읽고 필요한 말만 한다', false, '단체채팅·정보', '[{"conceptId":"exp.reaction","directionForOptionA":"a"},{"conceptId":"att.reading","directionForOptionA":"a"}]'::jsonb),
    ('107fc85f-8240-4539-a269-3e780629dc6f'::uuid, 'meeting-day', 10, '모임 당일 나는?', '모임 당일 이 사람은?', '일찍부터 분위기를 띄운다', '도착해서 자연스럽게 합류한다', false, '모임·진입', '[{"conceptId":"rel.entry","directionForOptionA":"a"}]'::jsonb),
    ('b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid, 'busy-mind', 1, '마음이 복잡한 날 나는?', '마음이 복잡한 날 이 사람은?', '누군가에게 말하며 정리한다', '혼자 시간을 보내며 정리한다', true, '감정·회복', '[{"conceptId":"exp.processing","directionForOptionA":"a"},{"conceptId":"reg.source","directionForOptionA":"a"}]'::jsonb),
    ('b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid, 'compliment', 2, '기분이 안 좋은 날 편한 사람이 물으면 나는?', '기분이 안 좋은 날 편한 사람이 물으면 이 사람은?', '비교적 바로 속마음을 꺼낸다', '몇 번 대화를 나누며 천천히 연다', false, '감정·숨김', '[{"conceptId":"rel.distance","directionForOptionA":"a"}]'::jsonb),
    ('b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid, 'big-choice', 3, '신경 쓰이는 일이 있으면 나는?', '신경 쓰이는 일이 있으면 이 사람은?', '같은 이야기를 여러 번 꺼낸다', '다른 일에 더 몰두한다', false, '걱정·생각', '[{"conceptId":"exp.processing","directionForOptionA":"a"}]'::jsonb),
    ('b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid, 'letdown', 4, '기대했던 일이 어긋난 직후 나는?', '기대했던 일이 어긋난 직후 이 사람은?', '아쉬움을 말로 표현한다', '다음 방법부터 찾는다', false, '실망·전환', '[{"conceptId":"exp.intensity","directionForOptionA":"a"},{"conceptId":"reg.transition","directionForOptionA":"b"}]'::jsonb),
    ('b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid, 'misunderstood', 5, '오해받았다고 느끼면 나는?', '오해받았다고 느끼면 이 사람은?', '그 자리에서 바로 풀려고 한다', '감정이 가라앉은 뒤 이야기한다', false, '오해·반응', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid, 'free-day', 6, '편한 사람과 단둘이 있으면 나는?', '편한 사람과 단둘이 있으면 이 사람은?', '사소한 이야기까지 많이 한다', '말없이 있어도 편하게 쉰다', false, '친밀한관계', '[{"conceptId":"exp.intensity","directionForOptionA":"a"}]'::jsonb),
    ('b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid, 'need-help', 7, '도움이 필요할 때 나는?', '도움이 필요할 때 이 사람은?', '구체적으로 부탁한다', '혼자 해본 뒤 부탁한다', false, '도움·반응', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid, 'new-start', 8, '걱정이 많아진 날 나는?', '걱정이 많아진 날 이 사람은?', '사소한 걸 자주 확인한다', '혼자 정리하는 시간이 길어진다', false, '걱정·준비', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid, 'attention', 9, '사람들이 나를 주목하면 나는?', '사람들이 이 사람을 주목하면?', '그 분위기를 즐기는 편이다', '조금 뒤로 물러나는 편이다', false, '주목·표현', '[{"conceptId":"exp.intensity","directionForOptionA":"a"}]'::jsonb),
    ('b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid, 'affection', 10, '좋아하는 사람에게 마음을 표현할 때 나는 주로?', '좋아하는 사람에게 마음을 표현할 때 이 사람은?', '말로 직접 전한다', '행동으로 자연스럽게 보여 준다', false, '애정·표현', '[{"conceptId":"exp.form","directionForOptionA":"b"}]'::jsonb),
    ('ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid, 'first-laugh', 1, '웃긴 일이 생기면 나는?', '웃긴 일이 생기면 이 사람은?', '바로 크게 반응한다', '한 번 곱씹고 터진다', true, '웃음·반응', '[{"conceptId":"exp.reaction","directionForOptionA":"a"},{"conceptId":"exp.intensity","directionForOptionA":"a"}]'::jsonb),
    ('ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid, 'storytelling', 2, '재밌는 이야기를 할 때 나는?', '재밌는 이야기를 할 때 이 사람은?', '상황을 자세히 살린다', '핵심만 빠르게 던진다', false, '유머·이야기', '[{"conceptId":"att.story","directionForOptionA":"a"}]'::jsonb),
    ('ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid, 'pun', 3, '말장난이 떠오르면 나는?', '말장난이 떠오르면 이 사람은?', '참지 못하고 바로 말한다', '타이밍이 맞을 때 꺼낸다', false, '유머·반응', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid, 'friend-joke', 4, '친구가 웃긴 말을 하면 나는?', '친구가 웃긴 말을 하면 이 사람은?', '더 크게 받아친다', '한참 웃고 다시 꺼낸다', false, '친구·웃음', '[{"conceptId":"exp.intensity","directionForOptionA":"a"}]'::jsonb),
    ('ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid, 'unexpected', 5, '예상 못 한 상황에서 나는?', '예상 못 한 상황에서 이 사람은?', '당황한 게 더 웃기다', '상황을 정리한 뒤 웃는다', false, '돌발·반응', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid, 'reference', 6, '예전에 웃긴 콘텐츠를 다시 보면 나는?', '예전에 웃긴 콘텐츠를 다시 보면 이 사람은?', '비슷한 추천을 따라 더 찾아본다', '일부러 다른 스타일의 웃음을 찾는다', false, '유머·기억', '[{"conceptId":"pref.discovery","directionForOptionA":"a"}]'::jsonb),
    ('ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid, 'quiet-laugh', 7, '진짜 웃길 때 나는?', '진짜 웃길 때 이 사람은?', '소리부터 크게 난다', '말없이 표정부터 바뀐다', false, '웃음·표현', '[{"conceptId":"exp.intensity","directionForOptionA":"a"}]'::jsonb),
    ('ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid, 'humor-style', 8, '취향에 맞는 유머 하나를 발견하면 나는?', '취향에 맞는 유머 하나를 발견하면 이 사람은?', '비슷한 스타일을 연달아 찾아본다', '정반대 스타일도 일부러 찾아본다', false, '유머·취향', '[{"conceptId":"pref.discovery","directionForOptionA":"a"}]'::jsonb),
    ('ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid, 'share-laugh', 9, '혼자 웃긴 걸 보면 나는?', '혼자 웃긴 걸 보면 이 사람은?', '누군가에게 보여 주고 싶다', '혼자 웃은 걸로도 충분하다', false, '유머·공유', '[{"conceptId":"reg.source","directionForOptionA":"a"}]'::jsonb),
    ('ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid, 'recover', 10, '너무 웃어서 진정해야 할 때 나는?', '너무 웃어서 진정해야 할 때 이 사람은?', '다른 이야기나 활동으로 자극을 바꾼다', '소리를 줄이고 가만히 숨을 고른다', false, '웃음·회복', '[{"conceptId":"reg.stimulus","directionForOptionA":"a"}]'::jsonb),
    ('ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid, 'conflict', 1, '서운한 일이 생기면 나는?', '서운한 일이 생기면 이 사람은?', '바로 이야기한다', '생각을 정리한 뒤 말한다', false, '친구·갈등', '[{"conceptId":"exp.reaction","directionForOptionA":"a"},{"conceptId":"exp.processing","directionForOptionA":"a"}]'::jsonb),
    ('ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid, 'reunion', 2, '오랜만에 친구를 만나면 나는?', '오랜만에 친구를 만나면 이 사람은?', '어제 본 듯 바로 편해진다', '근황부터 천천히 맞춰 간다', true, '재회·거리', '[{"conceptId":"rel.distance","directionForOptionA":"a"}]'::jsonb),
    ('ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid, 'plans', 3, '약속을 잡을 때 나는?', '약속을 잡을 때 이 사람은?', '미리 날짜를 정한다', '그때그때 편한 날을 본다', false, '친구·약속', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid, 'comfort', 4, '친구가 고민을 털어놓으면 나는?', '친구가 고민을 털어놓으면 이 사람은?', '먼저 끝까지 들어준다', '해결 방법부터 같이 찾는다', false, '친구·위로', '[{"conceptId":"coop.support","directionForOptionA":"b"}]'::jsonb),
    ('ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid, 'gathering', 5, '여러 친구가 모인 자리에서 나는?', '여러 친구가 모인 자리에서 이 사람은?', '먼저 분위기를 띄운다', '익숙한 사람 곁에서 시작한다', false, '친구·모임', '[{"conceptId":"rel.entry","directionForOptionA":"a"}]'::jsonb),
    ('ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid, 'reconnect', 6, '연락이 뜸해졌을 때 나는?', '연락이 뜸해졌을 때 이 사람은?', '짧게 안부부터 보낸다', '만날 약속부터 잡는다', false, '친구·연락', '[{"conceptId":"rel.cadence","directionForOptionA":"a"}]'::jsonb),
    ('ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid, 'memory', 7, '옛날 이야기가 나오면 나는?', '옛날 이야기가 나오면 이 사람은?', '구체적인 장면부터 떠올린다', '그때 느낀 감정부터 떠올린다', false, '친구·기억', '[{"conceptId":"att.memory","directionForOptionA":"a"}]'::jsonb),
    ('ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid, 'travel', 8, '친구와 여행 일정을 정할 때 나는?', '친구와 여행 일정을 정할 때 이 사람은?', '미리 계획을 세운다', '현장에서 그때그때 정한다', false, '친구·여행', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid, 'celebration', 9, '친구의 좋은 소식을 들으면 나는?', '친구의 좋은 소식을 들으면 이 사람은?', '바로 메시지로 마음을 전한다', '만났을 때 더 길게 축하한다', false, '친구·축하', '[{"conceptId":"rel.cadence","directionForOptionA":"a"},{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid, 'hard-day', 10, '힘든 날에 나는?', '힘든 날에 이 사람은?', '먼저 연락해 털어놓는다', '혼자 정리한 뒤 연락한다', false, '친구·회복', '[{"conceptId":"exp.processing","directionForOptionA":"a"},{"conceptId":"reg.source","directionForOptionA":"a"}]'::jsonb),
    ('9113ceed-fd0c-4523-bb14-316ee823e652'::uuid, 'reply-gap', 1, '메시지를 보낸 뒤 답이 늦으면 나는?', '메시지를 보낸 뒤 답이 늦으면 이 사람은?', '다른 일을 하며 기다린다', '필요하면 한 번 더 가볍게 묻는다', true, '메시지·기다림', '[{"conceptId":"rel.cadence","directionForOptionA":"b"}]'::jsonb),
    ('9113ceed-fd0c-4523-bb14-316ee823e652'::uuid, 'first-text', 2, '먼저 연락하고 싶을 때 나는?', '먼저 연락하고 싶을 때 이 사람은?', '짧은 안부부터 보낸다', '보낼 이유가 생길 때까지 기다린다', false, '연락·진입', '[{"conceptId":"rel.entry","directionForOptionA":"a"},{"conceptId":"rel.cadence","directionForOptionA":"a"}]'::jsonb),
    ('9113ceed-fd0c-4523-bb14-316ee823e652'::uuid, 'emoji-reply', 3, '할 말은 많은데 바쁠 때 나는?', '할 말은 많은데 바쁠 때 이 사람은?', '이모지로 먼저 신호를 남긴다', '여유 생긴 뒤 제대로 답한다', false, '메시지·표현', '[{"conceptId":"exp.form","directionForOptionA":"a"},{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('9113ceed-fd0c-4523-bb14-316ee823e652'::uuid, 'long-message', 4, '긴 메시지를 받으면 나는?', '긴 메시지를 받으면 이 사람은?', '처음부터 순서대로 읽으며 답한다', '가장 중요한 질문부터 찾아 답한다', false, '메시지·정보', '[{"conceptId":"att.reading","directionForOptionA":"a"}]'::jsonb),
    ('9113ceed-fd0c-4523-bb14-316ee823e652'::uuid, 'typo', 5, '오타를 발견하면 나는?', '오타를 발견하면 이 사람은?', '바로 수정해서 다시 보낸다', '뜻이 통하면 그냥 둔다', false, '메시지·검토', '[{"conceptId":"dec.revision","directionForOptionA":"b"}]'::jsonb),
    ('9113ceed-fd0c-4523-bb14-316ee823e652'::uuid, 'late-night', 6, '늦은 밤 연락이 오면 나는?', '늦은 밤 연락이 오면 이 사람은?', '지금 할 수 있는 만큼 답한다', '다음 날 정신 있을 때 답한다', false, '메시지·시간', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('9113ceed-fd0c-4523-bb14-316ee823e652'::uuid, 'reaction', 7, '재밌는 걸 발견하면 나는?', '재밌는 걸 발견하면 이 사람은?', '바로 공유한다', '나중에 모아서 보낸다', false, '콘텐츠·연락', '[{"conceptId":"exp.reaction","directionForOptionA":"a"}]'::jsonb),
    ('9113ceed-fd0c-4523-bb14-316ee823e652'::uuid, 'voice-note', 8, '텍스트로 설명이 길어질 것 같으면 나는?', '텍스트로 설명이 길어질 것 같으면 이 사람은?', '음성이나 통화로 바꾼다', '글로 차근차근 적는다', false, '메시지·표현', '[{"conceptId":"exp.form","directionForOptionA":"a"}]'::jsonb),
    ('9113ceed-fd0c-4523-bb14-316ee823e652'::uuid, 'read-receipt', 9, '읽음 표시를 본 뒤 나는?', '읽음 표시를 본 뒤 이 사람은?', '상대 상황을 생각하며 기다린다', '답이 필요한 때를 다시 알려 준다', false, '메시지·기다림', '[{"conceptId":"rel.cadence","directionForOptionA":"b"}]'::jsonb),
    ('9113ceed-fd0c-4523-bb14-316ee823e652'::uuid, 'goodbye', 10, '대화를 마칠 때 나는?', '대화를 마칠 때 이 사람은?', '다음 이야기를 남겨 둔다', '깔끔하게 인사하고 끝낸다', false, '대화·종료', '[{"conceptId":"dec.openness","directionForOptionA":"b"}]'::jsonb),
    ('aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid, 'reset-space', 1, '집에 돌아와 일상 모드를 바꿀 때 나는?', '집에 돌아와 일상 모드를 바꿀 때 이 사람은?', '씻고 옷을 갈아입으며 바로 전환한다', '잠깐 앉아 바깥의 여운부터 정리한다', true, '귀가·공간', '[{"conceptId":"reg.transition","directionForOptionA":"a"}]'::jsonb),
    ('aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid, 'lighting', 2, '피곤한 밤에 방 분위기를 바꾼다면?', '피곤한 밤에 방 분위기를 바꿀 때 이 사람은?', '조명을 밝히거나 음악을 틀어 전환한다', '불빛과 소리를 줄여 가라앉힌다', false, '공간·빛', '[{"conceptId":"reg.stimulus","directionForOptionA":"a"}]'::jsonb),
    ('aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid, 'sound', 3, '집에서 나는?', '집에서 이 사람은?', '무언가 틀어 두는 편이다', '조용한 편이 좋다', false, '공간·소리', '[{"conceptId":"reg.stimulus","directionForOptionA":"a"}]'::jsonb),
    ('aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid, 'tidy', 4, '정리가 필요해 보이면 나는?', '정리가 필요해 보이면 이 사람은?', '바로 눈에 보이는 곳부터 한다', '각 잡고 한 번에 한다', false, '공간·정리', '[{"conceptId":"act.start","directionForOptionA":"a"}]'::jsonb),
    ('aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid, 'blanket', 5, '집에서 쉬기 시작할 때 나는?', '집에서 쉬기 시작할 때 이 사람은?', '편한 옷으로 완전히 갈아입는다', '지금 차림 그대로 편하게 앉는다', false, '귀가·전환', '[{"conceptId":"reg.transition","directionForOptionA":"a"}]'::jsonb),
    ('aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid, 'window', 6, '방이 답답해 손보고 싶을 때 나는?', '방이 답답해 손보고 싶을 때 이 사람은?', '창문 하나부터 열어 변화를 시작한다', '빛과 온도와 공기를 전체적으로 살핀다', false, '공간·환경', '[{"conceptId":"act.start","directionForOptionA":"a"}]'::jsonb),
    ('aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid, 'plant', 7, '방에 쓸 수 있는 작은 예산이 생기면?', '방에 쓸 수 있는 작은 예산이 생기면 이 사람은?', '오래 마음에 들 좋은 하나를 고른다', '작은 장식 여러 개로 분위기를 만든다', false, '공간·선택', '[{"conceptId":"pref.focus","directionForOptionA":"a"}]'::jsonb),
    ('aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid, 'desk', 8, '책상 위가 복잡해지면 나는?', '책상 위가 복잡해지면 이 사람은?', '정리해야 집중된다', '익숙한 어수선함도 괜찮다', false, '공간·집중', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid, 'scent', 9, '방에 새로운 분위기를 들이고 싶다면?', '방에 새로운 분위기를 들이고 싶을 때 이 사람은?', '좋아하던 향이나 음악을 더 깊게 찾는다', '일부러 전혀 다른 조합을 찾아본다', false, '공간·환경', '[{"conceptId":"pref.discovery","directionForOptionA":"a"}]'::jsonb),
    ('aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid, 'guest', 10, '지친 손님이 집에 찾아오면 나는?', '지친 손님이 집에 찾아오면 이 사람은?', '먹을 것처럼 필요한 도움부터 챙긴다', '편히 앉혀 이야기를 먼저 들어준다', false, '공간·돌봄', '[{"conceptId":"coop.support","directionForOptionA":"a"}]'::jsonb),
    ('db1136e2-c40b-4354-800a-7938cc73dc47'::uuid, 'treat', 1, '나를 기분 좋게 하는 작은 소비는?', '이 사람을 기분 좋게 하는 작은 소비는?', '평소보다 좋은 한 가지를 고른다', '여러 개의 작은 즐거움을 고른다', true, '소비·만족', '[{"conceptId":"pref.focus","directionForOptionA":"a"}]'::jsonb),
    ('db1136e2-c40b-4354-800a-7938cc73dc47'::uuid, 'coffee', 2, '카페에서 나는?', '카페에서 이 사람은?', '늘 좋아하는 메뉴를 고른다', '계절 메뉴를 한 번 시도한다', false, '카페·취향', '[{"conceptId":"pref.stability","directionForOptionA":"a"},{"conceptId":"dec.experiment","directionForOptionA":"a"}]'::jsonb),
    ('db1136e2-c40b-4354-800a-7938cc73dc47'::uuid, 'gift', 3, '나에게 작은 선물을 고를 때 나는?', '자신에게 작은 선물을 고를 때 이 사람은?', '전부터 좋아하던 것을 고른다', '그날 새롭게 끌린 것을 고른다', false, '소비·보상', '[{"conceptId":"pref.stability","directionForOptionA":"a"}]'::jsonb),
    ('db1136e2-c40b-4354-800a-7938cc73dc47'::uuid, 'upgrade', 4, '더 좋은 선택지가 보이면 나는?', '더 좋은 선택지가 보이면 이 사람은?', '값어치를 따져 업그레이드한다', '기본으로도 충분한지 본다', false, '소비·검토', '[{"conceptId":"dec.revision","directionForOptionA":"b"}]'::jsonb),
    ('db1136e2-c40b-4354-800a-7938cc73dc47'::uuid, 'comfort', 5, '같은 예산으로 집을 편하게 만든다면?', '같은 예산으로 집을 편하게 만들 때 이 사람은?', '촉감 좋은 하나에 집중한다', '향과 빛 같은 작은 변화들을 더한다', false, '공간·만족', '[{"conceptId":"pref.focus","directionForOptionA":"a"}]'::jsonb),
    ('db1136e2-c40b-4354-800a-7938cc73dc47'::uuid, 'meal', 6, '혼자 맛있는 걸 먹을 때 나는?', '혼자 맛있는 걸 먹을 때 이 사람은?', '제대로 차려서 먹는다', '편한 방식으로 즐긴다', false, '식사·준비', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('db1136e2-c40b-4354-800a-7938cc73dc47'::uuid, 'collect', 7, '마음에 드는 물건을 발견하면 나는?', '마음에 드는 물건을 발견하면 이 사람은?', '비슷한 걸 모으고 싶어진다', '하나만 골라 오래 쓴다', false, '수집·만족', '[{"conceptId":"pref.focus","directionForOptionA":"b"}]'::jsonb),
    ('db1136e2-c40b-4354-800a-7938cc73dc47'::uuid, 'occasion', 8, '특별한 날이 아니어도 일을 하나 끝냈다면?', '특별한 날이 아니어도 일을 하나 끝내면 이 사람은?', '작은 보상으로 잠깐 마무리한다', '기분을 이어 바로 다음 일을 한다', false, '보상·전환', '[{"conceptId":"reg.transition","directionForOptionA":"b"}]'::jsonb),
    ('db1136e2-c40b-4354-800a-7938cc73dc47'::uuid, 'recommend', 9, '좋은 걸 발견하면 나는?', '좋은 걸 발견하면 이 사람은?', '누구에게든 추천하고 싶다', '나만의 목록에 넣어 둔다', false, '추천·표현', '[{"conceptId":"exp.intensity","directionForOptionA":"a"}]'::jsonb),
    ('db1136e2-c40b-4354-800a-7938cc73dc47'::uuid, 'memory', 10, '돈을 쓰는 좋은 순간에 나는?', '돈을 쓰는 좋은 순간에 이 사람은?', '사진이나 기록을 남기며 즐긴다', '먼저 충분히 즐긴 뒤 하나만 남긴다', false, '소비·기억', '[{"conceptId":"att.experience","directionForOptionA":"a"}]'::jsonb),
    ('3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid, 'snack-moment', 1, '간식이 당길 때 나는?', '간식이 당길 때 이 사람은?', '정해 둔 최애를 찾는다', '그날 당기는 맛을 고른다', true, '간식·취향', '[{"conceptId":"pref.stability","directionForOptionA":"a"}]'::jsonb),
    ('3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid, 'sweet-salty', 2, '둘이 단짠 간식을 고를 때 나는?', '둘이 단짠 간식을 고를 때 이 사람은?', '같이 먹을 한 가지 맛에 맞춘다', '서로 다른 맛을 골라 나눠 먹는다', false, '간식·맛', '[{"conceptId":"coop.sync","directionForOptionA":"a"}]'::jsonb),
    ('3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid, 'share', 3, '간식을 나눌 때 나는?', '간식을 나눌 때 이 사람은?', '내가 좋아하는 걸 권한다', '상대 취향을 먼저 묻는다', false, '간식·추천', '[{"conceptId":"pref.stability","directionForOptionA":"a"}]'::jsonb),
    ('3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid, 'movie-snack', 4, '영화를 볼 간식 예산이 정해져 있다면?', '영화를 볼 간식 예산이 정해져 있다면 이 사람은?', '가장 먹고 싶은 하나를 제대로 고른다', '여러 맛을 조금씩 고른다', false, '간식·선택', '[{"conceptId":"pref.focus","directionForOptionA":"a"}]'::jsonb),
    ('3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid, 'new-flavor', 5, '처음 보는 맛을 만나면 나는?', '처음 보는 맛을 만나면 이 사람은?', '궁금해서 시도한다', '후기를 보고 결정한다', false, '간식·시도', '[{"conceptId":"dec.experiment","directionForOptionA":"b"}]'::jsonb),
    ('3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid, 'last-bite', 6, '마지막 한 입이 남으면 나는?', '마지막 한 입이 남으면 이 사람은?', '지금 먹어 깔끔하게 끝낸다', '나중을 위해 남겨 둔다', false, '간식·종료', '[{"conceptId":"dec.openness","directionForOptionA":"a"}]'::jsonb),
    ('3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid, 'stock', 7, '집에 간식을 둘 때 나는?', '집에 간식을 둘 때 이 사람은?', '없으면 불안한 걸 쟁인다', '그때그때 필요한 만큼 산다', false, '간식·준비', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid, 'pairing', 8, '음료와 간식 조합을 새로 찾을 때 나는?', '음료와 간식 조합을 새로 찾을 때 이 사람은?', '잘 맞는 추천 조합을 따라가 본다', '일부러 뜻밖의 조합을 만들어 본다', false, '간식·조합', '[{"conceptId":"pref.discovery","directionForOptionA":"a"}]'::jsonb),
    ('3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid, 'craving', 9, '먹고 싶은 게 있는데 없으면 나는?', '먹고 싶은 게 있는데 없으면 이 사람은?', '비슷한 걸 찾아 해결한다', '다음 기회까지 기다린다', false, '간식·변경', '[{"conceptId":"act.adjustment","directionForOptionA":"a"}]'::jsonb),
    ('3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid, 'gift-snack', 10, '누군가에게 간식을 고른다면 나는?', '누군가에게 간식을 고른다면 이 사람은?', '안전하게 좋아할 만한 걸 고른다', '새롭게 좋아할 걸 골라 본다', false, '간식·선물', '[{"conceptId":"dec.experiment","directionForOptionA":"a"}]'::jsonb),
    ('62c5934c-b9b7-4df0-a690-c36399237735'::uuid, 'recharge', 1, '사람들과 오래 보낸 뒤 나는?', '사람들과 오래 보낸 뒤 이 사람은?', '누군가와 더 이야기하며 마무리한다', '혼자 조용히 있어야 회복된다', true, '모임·회복', '[{"conceptId":"reg.source","directionForOptionA":"a"}]'::jsonb),
    ('62c5934c-b9b7-4df0-a690-c36399237735'::uuid, 'party-entry', 2, '모임에 도착하면 나는?', '모임에 도착하면 이 사람은?', '여러 사람에게 먼저 인사한다', '익숙한 사람부터 찾는다', false, '모임·관계', '[{"conceptId":"rel.entry","directionForOptionA":"a"},{"conceptId":"rel.range","directionForOptionA":"a"}]'::jsonb),
    ('62c5934c-b9b7-4df0-a690-c36399237735'::uuid, 'new-person', 3, '처음 보는 사람이 있으면 나는?', '처음 보는 사람이 있으면 이 사람은?', '궁금한 걸 먼저 묻는다', '대화 흐름을 보며 합류한다', false, '낯선사람', '[{"conceptId":"rel.entry","directionForOptionA":"a"}]'::jsonb),
    ('62c5934c-b9b7-4df0-a690-c36399237735'::uuid, 'small-talk', 4, '아는 사람이 적은 모임에서 나는?', '아는 사람이 적은 모임에서 이 사람은?', '소개받으며 자리를 넓힌다', '한 사람과 대화를 오래 잇는다', false, '모임·관계', '[{"conceptId":"rel.range","directionForOptionA":"a"}]'::jsonb),
    ('62c5934c-b9b7-4df0-a690-c36399237735'::uuid, 'week-plan', 5, '약속이 연달아 잡히면 나는?', '약속이 연달아 잡히면 이 사람은?', '재밌을 것 같아 기대한다', '중간에 비는 시간을 만든다', false, '약속·회복', '[{"conceptId":"reg.source","directionForOptionA":"a"}]'::jsonb),
    ('62c5934c-b9b7-4df0-a690-c36399237735'::uuid, 'one-on-one', 6, '모임에서 대화할 시간이 생기면 나는?', '모임에서 대화할 시간이 생기면 이 사람은?', '여러 사람과 짧게 이야기를 잇는다', '한 사람과 긴 이야기를 나눈다', false, '모임·피로', '[{"conceptId":"rel.range","directionForOptionA":"a"}]'::jsonb),
    ('62c5934c-b9b7-4df0-a690-c36399237735'::uuid, 'after-cancel', 7, '모임에서 맡기 편한 역할은?', '모임에서 이 사람에게 편한 역할은?', '사람들을 자연스럽게 이어 주기', '필요한 걸 조용히 챙기기', false, '모임·역할', '[{"conceptId":"coop.role","directionForOptionA":"a"}]'::jsonb),
    ('62c5934c-b9b7-4df0-a690-c36399237735'::uuid, 'hosting', 8, '사람들을 초대하는 날 나는?', '사람들을 초대하는 날 이 사람은?', '각자 편하게 놀게 만든다', '함께할 흐름을 준비한다', false, '초대·준비', '[{"conceptId":"act.preparation","directionForOptionA":"b"}]'::jsonb),
    ('62c5934c-b9b7-4df0-a690-c36399237735'::uuid, 'leave-time', 9, '모임을 마칠 때 나는?', '모임을 마칠 때 이 사람은?', '마지막까지 남아 이야기한다', '좋았을 때 먼저 인사한다', false, '모임·회복', '[{"conceptId":"reg.source","directionForOptionA":"a"}]'::jsonb),
    ('62c5934c-b9b7-4df0-a690-c36399237735'::uuid, 'reset', 10, '사람 많은 날 집에 돌아오면 나는?', '사람 많은 날 집에 돌아오면 이 사람은?', '가볍게 움직이며 기분을 바꾼다', '불빛과 소리를 줄여 쉰다', false, '모임·회복', '[{"conceptId":"reg.motion","directionForOptionA":"a"},{"conceptId":"reg.stimulus","directionForOptionA":"a"}]'::jsonb),
    ('18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid, 'sudden-invite', 1, '지금 보자는 연락이 오면 나는?', '지금 보자는 연락이 오면 이 사람은?', '가능하면 바로 움직인다', '준비할 시간을 먼저 본다', true, '즉흥약속', '[{"conceptId":"act.preparation","directionForOptionA":"b"}]'::jsonb),
    ('18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid, 'meeting-place', 2, '약속 장소를 정할 때 나는?', '약속 장소를 정할 때 이 사람은?', '딱 떠오르는 곳을 말한다', '서로 편한 중간을 찾는다', false, '약속·애매함', '[{"conceptId":"dec.convergence","directionForOptionA":"a"},{"conceptId":"coop.ambiguity","directionForOptionA":"b"}]'::jsonb),
    ('18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid, 'one-more', 3, '재밌는 시간이 끝날 무렵 나는?', '재밌는 시간이 끝날 무렵 이 사람은?', '한 곳 더 가자고 한다', '좋을 때 다음을 기약한다', false, '약속·종료', '[{"conceptId":"dec.openness","directionForOptionA":"b"}]'::jsonb),
    ('18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid, 'weather-change', 4, '날씨 때문에 계획이 바뀌면 나는?', '날씨 때문에 계획이 바뀌면 이 사람은?', '다른 할 일을 바로 고른다', '그 상황에 맞춰 천천히 바꾼다', false, '약속·전환', '[{"conceptId":"reg.transition","directionForOptionA":"a"}]'::jsonb),
    ('18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid, 'unexpected-guest', 5, '예상 못 한 합류자가 생기면 나는?', '예상 못 한 합류자가 생기면 이 사람은?', '더 재밌어질 것 같아 반긴다', '원래 약속의 결을 먼저 본다', false, '약속·변경', '[{"conceptId":"act.adjustment","directionForOptionA":"a"}]'::jsonb),
    ('18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid, 'late-start', 6, '약속 시간에 늦을 것 같으면 나는?', '약속 시간에 늦을 것 같으면 이 사람은?', '바로 알려 기다릴 시간을 줄인다', '새 도착 시간을 확인해 정확히 알린다', false, '약속·연락', '[{"conceptId":"exp.reaction","directionForOptionA":"a"},{"conceptId":"act.preparation","directionForOptionA":"b"}]'::jsonb),
    ('18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid, 'new-place', 7, '처음 보는 장소를 고를 때 나는?', '처음 보는 장소를 고를 때 이 사람은?', '호기심으로 일단 가 본다', '후기와 정보를 먼저 본다', false, '장소·시도', '[{"conceptId":"dec.experiment","directionForOptionA":"b"}]'::jsonb),
    ('18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid, 'budget', 8, '즉흥 약속의 비용은 나는?', '즉흥 약속의 비용은 이 사람은?', '재밌으면 조금 더 쓸 수 있다', '편한 범위를 먼저 정한다', false, '약속·비용', '[{"conceptId":"act.preparation","directionForOptionA":"b"}]'::jsonb),
    ('18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid, 'surprise', 9, '작은 깜짝 약속을 만든다면 나는?', '작은 깜짝 약속을 만들 때 이 사람은?', '여러 사람이 함께 즐길 장면을 만든다', '한 사람에게 꼭 맞는 장면을 깊게 준비한다', false, '약속·표현', '[{"conceptId":"rel.range","directionForOptionA":"a"}]'::jsonb),
    ('18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid, 'memory-plan', 10, '좋은 즉흥 약속은 내게?', '이 사람에게 좋은 즉흥 약속은?', '예상 못 한 장면이 생긴 날', '서로 편하게 웃은 날', false, '약속·기억', '[{"conceptId":"att.memory","directionForOptionA":"a"}]'::jsonb),
    ('7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid, 'morning-start', 1, '하루를 시작할 때 나는?', '하루를 시작할 때 이 사람은?', '정해 둔 순서가 있어야 편하다', '그날 기분에 따라 시작한다', true, '아침·일상', '[{"conceptId":"act.routine","directionForOptionA":"a"}]'::jsonb),
    ('7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid, 'first-sound', 2, '아침에 가장 먼저 찾는 건?', '이 사람이 아침에 가장 먼저 찾는 건?', '조용한 시간', '음악이나 소리', false, '아침·자극', '[{"conceptId":"reg.stimulus","directionForOptionA":"b"}]'::jsonb),
    ('7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid, 'to-do', 3, '할 일을 기억하는 방식은?', '이 사람이 할 일을 기억하는 방식은?', '적어 두고 지운다', '머릿속 우선순위를 따른다', false, '할일·정보', '[{"conceptId":"act.preparation","directionForOptionA":"a"},{"conceptId":"att.reading","directionForOptionA":"a"}]'::jsonb),
    ('7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid, 'reset', 4, '흐트러진 하루를 되돌릴 때 나는?', '흐트러진 하루를 되돌릴 때 이 사람은?', '작은 것부터 하나 끝낸다', '잠깐 멈추고 다시 계획한다', false, '일상·시작', '[{"conceptId":"act.start","directionForOptionA":"a"}]'::jsonb),
    ('7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid, 'walk', 5, '잠깐 바람 쐴 때 나는?', '잠깐 바람 쐴 때 이 사람은?', '목적지를 정하고 걷는다', '발길 가는 대로 걷는다', false, '산책·준비', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid, 'music', 6, '집중할 때 나는?', '집중할 때 이 사람은?', '늘 듣는 걸 반복한다', '새로운 걸 틀어 분위기를 바꾼다', false, '집중·취향', '[{"conceptId":"pref.familiarity","directionForOptionA":"a"},{"conceptId":"dec.experiment","directionForOptionA":"a"}]'::jsonb),
    ('7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid, 'little-reward', 7, '해야 할 일을 끝내면 나는?', '해야 할 일을 끝내면 이 사람은?', '작은 보상을 챙긴다', '바로 다음 일로 넘어간다', false, '완료·전환', '[{"conceptId":"reg.transition","directionForOptionA":"b"}]'::jsonb),
    ('7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid, 'night-close', 8, '하루를 마무리할 때 나는?', '하루를 마무리할 때 이 사람은?', '쓴 물건을 제자리에 둔다', '내일 아침에 한 번에 정리한다', false, '밤·일상', '[{"conceptId":"act.routine","directionForOptionA":"a"}]'::jsonb),
    ('7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid, 'week-reset', 9, '새 주가 시작되기 전 나는?', '새 주가 시작되기 전 이 사람은?', '가방이나 옷부터 챙겨 둔다', '아침에 필요한 것부터 찾는다', false, '주간·준비', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid, 'broken-routine', 10, '루틴이 깨졌을 때 나는?', '루틴이 깨졌을 때 이 사람은?', '빠르게 원래대로 돌아간다', '새로운 리듬으로 받아들인다', false, '일상·변경', '[{"conceptId":"act.routine","directionForOptionA":"a"},{"conceptId":"act.adjustment","directionForOptionA":"b"}]'::jsonb),
    ('be9db225-95d3-4da7-8ace-4d8373c17108'::uuid, 'packing', 1, '여행 짐을 쌀 때 나는?', '여행 짐을 쌀 때 이 사람은?', '필요한 걸 목록으로 챙긴다', '가방 공간을 보며 감으로 챙긴다', true, '여행·준비', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('be9db225-95d3-4da7-8ace-4d8373c17108'::uuid, 'arrival', 2, '도착하자마자 나는?', '도착하자마자 이 사람은?', '짐부터 풀고 동선을 본다', '일단 주변부터 구경한다', false, '여행·도착', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('be9db225-95d3-4da7-8ace-4d8373c17108'::uuid, 'map', 3, '길을 찾을 때 나는?', '길을 찾을 때 이 사람은?', '지도와 후기를 미리 본다', '발길 가는 쪽을 따라간다', false, '여행·탐색', '[{"conceptId":"act.preparation","directionForOptionA":"a"},{"conceptId":"dec.experiment","directionForOptionA":"a"}]'::jsonb),
    ('be9db225-95d3-4da7-8ace-4d8373c17108'::uuid, 'food', 4, '여행지 식당을 고를 때 나는?', '여행지 식당을 고를 때 이 사람은?', '대표 메뉴부터 먹어 본다', '현지에서 눈에 띈 곳에 들어간다', false, '여행·식사', '[{"conceptId":"dec.experiment","directionForOptionA":"a"}]'::jsonb),
    ('be9db225-95d3-4da7-8ace-4d8373c17108'::uuid, 'open-hour', 5, '여행지에서 잠깐 시간이 비면 나는?', '여행지에서 잠깐 시간이 비면 이 사람은?', '가까운 곳을 하나 더 본다', '앉아서 그곳 분위기를 즐긴다', false, '여행·회복', '[{"conceptId":"reg.motion","directionForOptionA":"a"}]'::jsonb),
    ('be9db225-95d3-4da7-8ace-4d8373c17108'::uuid, 'change', 6, '일정이 어그러지면 나는?', '일정이 어그러지면 이 사람은?', '대안을 빠르게 찾는다', '뜻밖의 시간으로 받아들인다', false, '여행·변경', '[{"conceptId":"act.adjustment","directionForOptionA":"a"}]'::jsonb),
    ('be9db225-95d3-4da7-8ace-4d8373c17108'::uuid, 'souvenir', 7, '여행지에서 기억하고 싶은 장면이 생기면 나는?', '여행지에서 기억하고 싶은 장면이 생기면 이 사람은?', '그 자리에서 사진이나 기념을 남긴다', '먼저 충분히 즐긴 뒤 하나를 남긴다', false, '여행·기록', '[{"conceptId":"att.experience","directionForOptionA":"a"}]'::jsonb),
    ('be9db225-95d3-4da7-8ace-4d8373c17108'::uuid, 'morning', 8, '여행 중 아침 나는?', '여행 중 아침 이 사람은?', '일찍 시작해 하루를 길게 쓴다', '천천히 일어나 여유를 챙긴다', false, '여행·아침', '[{"conceptId":"reg.motion","directionForOptionA":"a"},{"conceptId":"reg.transition","directionForOptionA":"a"}]'::jsonb),
    ('be9db225-95d3-4da7-8ace-4d8373c17108'::uuid, 'detour', 9, '가고 싶던 곳이 멀어 보이면 나는?', '가고 싶던 곳이 멀어 보이면 이 사람은?', '그래도 루트를 맞춰 간다', '가까운 즐길 거리를 찾는다', false, '여행·변경', '[{"conceptId":"act.adjustment","directionForOptionA":"b"}]'::jsonb),
    ('be9db225-95d3-4da7-8ace-4d8373c17108'::uuid, 'last-night', 10, '여행 마지막 밤 나는?', '여행 마지막 밤 이 사람은?', '다음 날을 위해 정리한다', '마지막까지 밖에서 논다', false, '여행·전환', '[{"conceptId":"reg.transition","directionForOptionA":"a"}]'::jsonb),
    ('f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid, 'free-morning', 1, '아무 일정 없는 토요일 아침 나는?', '아무 일정 없는 토요일 아침 이 사람은?', '일단 밖으로 나갈 이유를 찾는다', '침대에서 천천히 하루를 연다', true, '주말·시작', '[{"conceptId":"reg.motion","directionForOptionA":"a"},{"conceptId":"reg.transition","directionForOptionA":"a"}]'::jsonb),
    ('f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid, 'last-minute', 2, '주말 약속이 하나 생기면 나는?', '주말 약속이 하나 생기면 이 사람은?', '앞뒤로 다른 계획도 붙인다', '그 약속만 두고 여유를 남긴다', false, '주말·계획', '[{"conceptId":"pref.focus","directionForOptionA":"b"}]'::jsonb),
    ('f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid, 'rest-plan', 3, '쉬는 날을 앞두고 나는?', '쉬는 날을 앞두고 이 사람은?', '하고 싶은 걸 미리 적어 둔다', '그날 기분에 맡긴다', false, '주말·준비', '[{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid, 'home-or-out', 4, '주말 오후에 나는 더 자주?', '주말 오후에 이 사람은 더 자주?', '새로운 동네를 돌아다닌다', '익숙한 곳에서 시간을 보낸다', false, '주말·탐색', '[{"conceptId":"pref.familiarity","directionForOptionA":"b"},{"conceptId":"dec.experiment","directionForOptionA":"b"}]'::jsonb),
    ('f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid, 'weather', 5, '날씨가 좋다는 말을 들으면 나는?', '날씨가 좋다는 말을 들으면 이 사람은?', '밖에 나갈 약속을 만든다', '창문 열고 집에서도 즐긴다', false, '주말·활동', '[{"conceptId":"reg.motion","directionForOptionA":"a"}]'::jsonb),
    ('f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid, 'late-lunch', 6, '늦은 점심을 고를 때 나는?', '늦은 점심을 고를 때 이 사람은?', '처음 보는 메뉴를 시도한다', '확실히 좋아하는 메뉴를 고른다', false, '주말·식사', '[{"conceptId":"pref.familiarity","directionForOptionA":"b"},{"conceptId":"dec.experiment","directionForOptionA":"b"}]'::jsonb),
    ('f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid, 'one-more-episode', 7, '재밌는 걸 보기 시작하면 나는?', '재밌는 걸 보기 시작하면 이 사람은?', '정한 만큼만 보고 멈춘다', '한 번만 더를 여러 번 한다', false, '주말·일상', '[{"conceptId":"act.routine","directionForOptionA":"a"},{"conceptId":"dec.openness","directionForOptionA":"a"}]'::jsonb),
    ('f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid, 'sunday-night', 8, '일요일 저녁이 되면 나는?', '일요일 저녁이 되면 이 사람은?', '다음 주 준비를 조금 한다', '마지막까지 주말에 집중한다', false, '주말·전환', '[{"conceptId":"reg.transition","directionForOptionA":"a"},{"conceptId":"act.preparation","directionForOptionA":"a"}]'::jsonb),
    ('f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid, 'mini-adventure', 9, '멀리 못 가는 날 나는?', '멀리 못 가는 날 이 사람은?', '가까운 곳에서 새 코스를 만든다', '집에서 좋아하는 걸 꺼낸다', false, '주말·탐색', '[{"conceptId":"pref.familiarity","directionForOptionA":"b"}]'::jsonb),
    ('f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid, 'weekend-proof', 10, '주말이 잘 보냈다고 느끼는 순간은?', '이 사람이 주말을 잘 보냈다고 느끼는 순간은?', '새로운 장면이 생겼을 때', '제대로 쉬었다고 느낄 때', false, '주말·회복', '[{"conceptId":"reg.motion","directionForOptionA":"a"}]'::jsonb);

insert into public.pack_templates (
  id, slug, title, target_relationship, sensitivity, is_active
)
select id, slug, title, target_relationship, sensitivity, is_active
from expected_pack_templates
on conflict (id) do nothing;

insert into public.pack_versions (id, template_id, version, concept_version)
select id, template_id, version, concept_version
from expected_pack_versions
on conflict (id) do nothing;

insert into public.pack_cards (
  pack_version_id, id, position, owner_prompt, visitor_prompt, option_a,
  option_b, is_signature, concept_context, concept_signals
)
select
  expected.pack_version_id,
  expected.id,
  expected.position,
  expected.owner_prompt,
  expected.visitor_prompt,
  expected.option_a,
  expected.option_b,
  expected.is_signature,
  expected.concept_context,
  expected.concept_signals
from expected_pack_cards as expected
join public.pack_versions as version
  on version.id = expected.pack_version_id
 and version.published_at is null
on conflict (pack_version_id, id) do nothing;

do $pack_readback$
begin
  if (select count(*) from expected_pack_templates) <> 24
    or (select count(*) from expected_pack_versions) <> 24
    or (select count(*) from expected_pack_cards) <> 240
    or exists (
      select * from expected_pack_templates
      except
      select
        template.id, template.slug, template.title,
        template.target_relationship, template.sensitivity, template.is_active
      from public.pack_templates as template
      where template.id in (select id from expected_pack_templates)
    )
    or exists (
      select
        template.id, template.slug, template.title,
        template.target_relationship, template.sensitivity, template.is_active
      from public.pack_templates as template
      where template.id in (select id from expected_pack_templates)
      except
      select * from expected_pack_templates
    )
    or exists (
      select * from expected_pack_versions
      except
      select
        version.id, version.template_id, version.version,
        version.concept_version
      from public.pack_versions as version
      where version.id in (select id from expected_pack_versions)
    )
    or exists (
      select
        version.id, version.template_id, version.version,
        version.concept_version
      from public.pack_versions as version
      where version.id in (select id from expected_pack_versions)
      except
      select * from expected_pack_versions
    )
    or exists (
      select * from expected_pack_cards
      except
      select
        card.pack_version_id, card.id, card.position, card.owner_prompt,
        card.visitor_prompt, card.option_a, card.option_b, card.is_signature,
        card.concept_context, card.concept_signals
      from public.pack_cards as card
      where card.pack_version_id in (select id from expected_pack_versions)
    )
    or exists (
      select
        card.pack_version_id, card.id, card.position, card.owner_prompt,
        card.visitor_prompt, card.option_a, card.option_b, card.is_signature,
        card.concept_context, card.concept_signals
      from public.pack_cards as card
      where card.pack_version_id in (select id from expected_pack_versions)
      except
      select * from expected_pack_cards
    )
  then
    raise exception 'pack catalog canonical readback failed';
  end if;
end
$pack_readback$;

do $pack_publish$
declare
  publication record;
begin
  for publication in
    select version.id
    from expected_pack_versions as version
    join expected_pack_templates as template on template.id = version.template_id
    order by
      substring(version.version from '-v([0-9]+)$')::integer,
      template.slug
  loop
    if exists (
      select 1
      from public.pack_versions as version
      where version.id = publication.id
        and version.published_at is null
    ) then
      perform public.publish_pack_version(publication.id);
    end if;
  end loop;
end
$pack_publish$;

do $pack_postcheck$
begin
  if exists (
    select 1
    from expected_pack_versions as expected
    left join public.pack_versions as version on version.id = expected.id
    where version.published_at is null
  )
    or exists (
      select 1
      from (
        values
    ('630c20b9-460b-443b-b74b-865d1dfdf5fb'::uuid, '870126e1-572b-4ccc-a5e4-c10ef30c6dca'::uuid),
    ('f16e20a8-f2bd-4799-af68-689bbc36ebd5'::uuid, 'cd96e04f-e7a1-4fd6-90b6-1251292250ac'::uuid),
    ('75ccfdf6-bf0d-4fb8-b8a4-a8cb5f933701'::uuid, 'bc2dfcba-8e71-4b35-9c29-7f9403143a57'::uuid),
    ('0a9b7ee3-9556-448f-8719-329094601b1a'::uuid, 'f95e97d9-60cf-4789-9393-8bb6127456c8'::uuid),
    ('e517cc31-8a8c-4156-a2ae-7e8ddb3f6809'::uuid, 'b3e542f9-2d87-4d9a-a40b-8bc22b3e543e'::uuid),
    ('13131313-1313-4313-8313-131313131313'::uuid, '085347bd-67ff-4ec3-929a-2d7cfd3d300a'::uuid),
    ('15299196-d3bf-4f89-be1e-bcc1ea69a904'::uuid, 'a67b03c5-72a3-4903-a3af-7ec31f617989'::uuid),
    ('dec475db-00a1-43ea-91c5-75d32259fd6b'::uuid, '260c451e-cabb-457f-9666-553c752f000b'::uuid),
    ('4c3f9b04-48a2-4dda-a2f9-bfcc101a9565'::uuid, '9d46e755-cc50-4af1-a84d-9e6c153ab715'::uuid),
    ('12121212-1212-4212-8212-121212121212'::uuid, 'be46cad0-5ac8-46e4-8126-0f8529239d34'::uuid),
    ('2cb89681-7c7b-42c4-b1f3-4700d5c17cc0'::uuid, '645d9394-7ae6-4ea3-a8f1-8b5b02791268'::uuid),
    ('0e2ac6eb-55f4-40f2-b943-6de54125f6b3'::uuid, '107fc85f-8240-4539-a269-3e780629dc6f'::uuid),
    ('14141414-1414-4414-8414-141414141414'::uuid, 'b2c8d377-2dcd-4fff-b574-805b51bec93d'::uuid),
    ('f3505753-0118-4778-86fe-19e45d6ec73d'::uuid, 'ea4b7ee8-d9fe-44f6-96a4-33236af4e9d9'::uuid),
    ('11111111-1111-4111-8111-111111111111'::uuid, 'ff63ec5c-11de-456d-a3a2-28ad65758e0f'::uuid),
    ('0fbddb18-d125-429e-ad8f-d6581a3af762'::uuid, '9113ceed-fd0c-4523-bb14-316ee823e652'::uuid),
    ('a714df85-063e-44f5-a3e5-cc4d6af032bc'::uuid, 'aad5d67a-677e-47f7-b51e-40b4682976fc'::uuid),
    ('547524ff-9929-44ef-b6d0-70b152b2f1e2'::uuid, 'db1136e2-c40b-4354-800a-7938cc73dc47'::uuid),
    ('79c2f482-e254-41a5-9e27-296bf416a5d7'::uuid, '3634ecf7-173a-4e8c-b9b0-576cb63d3fe3'::uuid),
    ('b5a4e134-2704-40b6-8fa3-7ad47c13e833'::uuid, '62c5934c-b9b7-4df0-a690-c36399237735'::uuid),
    ('78b2ca60-1f42-4114-a6e0-22155c2d701c'::uuid, '18b161c2-1580-4b76-a8cc-e5c6d1b13c16'::uuid),
    ('9e0d1399-0314-497d-99aa-79926e226726'::uuid, '7eb27e42-4a34-4b5a-8f54-9baa0dc08516'::uuid),
    ('4502a4a8-7ba4-4d3d-9aae-6ca220c57658'::uuid, 'be9db225-95d3-4da7-8ace-4d8373c17108'::uuid),
    ('2166c7e7-0d4c-411b-bed2-fe3337a2d24c'::uuid, 'f7d0ada4-5558-43c1-b68b-1618c5d7d6c2'::uuid)
      ) as expected(template_id, version_id)
      join public.pack_templates as template on template.id = expected.template_id
      where template.published_version_id is distinct from expected.version_id
    )
  then
    raise exception 'pack catalog publication postcheck failed';
  end if;
end
$pack_postcheck$;

commit;
